ulaval/modul-components

src/components/list-item/list-item.html
src/components/list-item/list-item.scss
src/components/list-item/list-item.ts

Remove top and bottom padding if true

Add full-height prop to list-item component

---

package-lock.json
package.json

release 1.0.0-beta.18

---

src/components/tooltip/tooltip.ts

Set open property on mounted

---

.circleci/config.yml
.travis.yml

Solves CircleCI and Travis out of memory / timeout errors

Jest single thread for continuous integration

---

.circleci/config.yml
.travis.yml
src/components/menu-item/menu-item.scss

https://jira.dti.ulaval.ca/browse/ENA2-629

ENA2-629 - INT - Menu d'options

---

src/components/file-select/file-select.ts
src/components/file-upload/__snapshots__/file-upload.spec.ts.snap
src/components/file-upload/file-upload.html
src/directives/file-drop/file-drop.spec.ts
src/directives/file-drop/file-drop.ts

Keep store on destroy of file-select and file-drop when inside file-upload component

Bug fix: ENA2-815

---

src/components/input-style/input-style.scss

Correction de ce billet
https://jira.dti.ulaval.ca/browse/ENA2-599

 The letters "qypgj" are not completely visible in the textarea

---

package-lock.json
package.json

Release 1.0.0-beta,26
Version closed

release 1.0.0-beta.26

---

package-lock.json
package.json

Release 1.0.0-beta.27
https://jira.dti.ulaval.ca/projects/MODUL/versions/24094

release 1.0.0-beta.27

---

package-lock.json
package.json
src/styles/abstracts/_mixins.scss

release 1.0.0-beta.28
https://jira.dti.ulaval.ca/projects/MODUL/versions/24099

Release/1.0.0 beta.28

---

conf/webpack.config.js
openshift/Jenkinsfile
openshift/create-app.cmd
openshift/create-project.cmd
openshift/delete-app.cmd
openshift/delete-project.cmd
openshift/imagestream.yaml
openshift/reload-all.cmd
openshift/reload-app.cmd
openshift/template.yaml
openshift/update-template.cmd
package-lock.json
package.json

Provide everything needed to allow deploying of the testing app into OpenShift
- [ x] Include links to issues
No links

To deploy the testing app into OpenShift

---

src/components/icon-button/icon-button.scss

Enlever le l'effet du clique lorsque le bouton change d'état active/désactif
[MODUL-62](https://jira.dti.ulaval.ca/browse/MODUL-62)

Resolve blur effect

---

src/utils/http/http.ts

remove useless import
Found while testing old issue: https://github.com/ulaval/modul-components/issues/11

remove useless import

---

src/components/accordion/__snapshots__/accordion.spec.ts.snap
src/components/accordion/accordion.html
src/components/accordion/accordion.scss
src/components/accordion/accordion.ts

-- https://jira.dti.ulaval.ca/browse/MODUL-80
-- https://jira.dti.ulaval.ca/browse/P411-69
-- https://jira.dti.ulaval.ca/browse/P411-958
-- Add a 'dark' skin for the component

Add a 'dark' skin for the accordion

---

package-lock.json
package.json

release 1.0.0-beta.30
https://jira.dti.ulaval.ca/projects/MODUL/versions/24282

release 1.0.0-beta.30

---

src/components/navbar-item/navbar-item.scss

Remove separator for last menu item (simple skin)
https://jira.dti.ulaval.ca/browse/ENA2-1103
https://jira.dti.ulaval.ca/browse/MODUL-129

ENA2-1103 - navbar - Remove separator for last menu item

---

src/components/icon-button/icon-button.scss

Ajuster le padding du composant m-icon-bouton

---

src/assets/icons/sprites-default.svg
src/components/login/__snapshots__/login.spec.ts.snap
src/components/textfield/textfield.html
src/components/textfield/textfield.lang.fr.json
src/components/textfield/textfield.ts

Mettre les bons icônes pour le champs de saisie en mode "password"
[MODUL-16](https://jira.dti.ulaval.ca/browse/MODUL-16)

m-textfield password icons

---

src/components/file-upload/file-upload.ts

Mettre le bouton 'Ajouter' cliquable même si des fichiers sont en erreurs
[MODUL-136](https://jira.dti.ulaval.ca/browse/MODUL-136)

File-uploader, change disabled condition for 'Add' button

---

src/assets/icons/sprites-default.svg
src/components/icon-file/icon-file.ts

Ajout de nouvelles icônes pour le téléverseur
[MODUL-124](https://jira.dti.ulaval.ca/browse/MODUL-124)

Nouvelles icônes pour le téléverseur

---

src/components/popper/popper.ts

Switch click event to mouse up
[MODUL-104](https://jira.dti.ulaval.ca/browse/MODUL-104)

Change event listener in popper

---

src/components/accordion/accordion.html

Appuyer sur Enter, ferme ce dernier même si l'action vient d'un composant enfant (ENA2-1110)
-- Add `self` event modifiers to accordion template
- [x ] Include links to issues
-- https://jira.dti.ulaval.ca/browse/MODUL-141
-- https://jira.dti.ulaval.ca/browse/ENA2-1110

MODUL-141 - Enter, focus & Accordion

---

src/utils/logger/logger.ts

- [ x] Provide a small description of the changes introduced by this PR
Utiliser l'opérateur de décomposition sur les parametres optionnels
- [x ] Include links to issues
https://jira.dti.ulaval.ca/browse/MODUL-143

MODUL-143 - decomposer les parametre optionnels

---

src/components/file-upload/file-upload.scss

Enlever l'overflow hidden qui cache les pastilles.
[MODUL-144](https://jira.dti.ulaval.ca/browse/MODUL-144)

File-upload remove overflow hidden

---

src/components/checkbox/checkbox.html
src/components/checkbox/checkbox.scss
src/components/radio-group/radio-group.html
src/components/radio-group/radio-group.scss

Ajouter une marge au groupe de bouton radio pour que le message soit décollé.
[MODUL-135](https://jira.dti.ulaval.ca/browse/MODUL-135)

Espacement entre les messages et le radio-group & checkbox

---

src/directives/badge/badge.ts

Ajouter l'état warning dans la directive pastille
[MODUL-33](https://jira.dti.ulaval.ca/browse/MODUL-33)

Ajout de l'état warning

---

src/utils/file/file.ts

ajout de l'attribut url sur les MFile qui était censé être déjà disponible
https://jira.dti.ulaval.ca/browse/MODUL-156

ENA2-1131 ajout de l'attribut url sur les MFile qui était censé être déjà disponible

---

src/components/icon-button/icon-button.scss

-- Change color of dark skin
-- https://jira.dti.ulaval.ca/browse/MODUL-155
-- https://jira.dti.ulaval.ca/browse/ENA2-1276

MODUL-155 - ENA2-1276 - changer la couleur d'un icon-button skin dark

---

src/components/file-upload/file-upload.html
src/components/file-upload/file-upload.spec.ts
src/components/file-upload/file-upload.ts
src/directives/badge/badge.ts

Change failded status to error
[MODUL-154](https://jira.dti.ulaval.ca/browse/MODUL-154)

M-Badge - Rename failed to error

---

.github/CODEOWNERS

Add codeowners file
https://jira.dti.ulaval.ca/projects/MODUL/issues/MODUL-81?filter=allopenissues

Add codeowners file for MODUL

---

src/components/carousel-item/carousel-item.html
src/components/carousel-item/carousel-item.ts

-- add animationStart & animationDone event
-- https://jira.dti.ulaval.ca/browse/MODUL-170
-- https://jira.dti.ulaval.ca/browse/ENA2-988

modul-170_carousel-item - add events before and after item's animation

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md

Add Openshift deployment option in PR.
https://jira.dti.ulaval.ca/browse/MODUL-175

openshift request option

---

src/components/dropdown/dropdown.html
src/mixins/open-trigger/open-trigger.ts
src/mixins/portal/portal.ts

m-dialog @click on slot wasn't called when clicking on element
https://jira.dti.ulaval.ca/browse/MODUL-150
- m-dialog: fixed a bug that prevented @click handler from being called when clicking on a slot.

bugfix m-dialog @click on slot wasn't working.,

---

src/mixins/element-queries/element-queries.ts

Fix ReferenceError: event is not defined in Firefox
https://jira.dti.ulaval.ca/browse/MODUL-180

remove undeclared/unused event in element-queries mixin

---

package-lock.json
package.json

Change dependency mode for css-element-queries
https://jira.dti.ulaval.ca/browse/MODUL-182

css-element-queries from peer to dependency

---

.vscode/extensions.json
.vscode/settings.json

Add extension recommendations for modUL
https://jira.dti.ulaval.ca/browse/MODUL-187

Add extensions recommandation for modUL

---

src/components/checkbox/checkbox.sandbox.html
src/components/radio-group/radio-group.sandbox.html

added sandboxes for radio-group & checkbox
JP complète ça

merge sandboxes

---

package-lock.json
package.json

Hotfix for dropdown aligment
https://jira.dti.ulaval.ca/projects/MODUL/versions/24685

Hotfix/1.0.0 beta.36

---

src/components/file-upload/__snapshots__/file-upload.spec.ts.snap
src/components/file-upload/file-upload.html

voir le billet: https://jira.dti.ulaval.ca/browse/MODUL-212

MODUL-212 - correction m-link file-upload

---

src/components/message/message.sandbox.html
src/components/message/message.scss

little tweaks to icon and text vertical alignment
https://jira.dti.ulaval.ca/browse/ENA2-1507
https://jira.dti.ulaval.ca/browse/MODUL-220

MODUL-220 - little tweaks to icon and text vertical alignment

---

.github/CODEOWNERS

Add new codeowners to help for code reviews
No link, project management request

new codeowners

---

src/directives/draggable/draggable.ts

… on a button or a link within the draggable.
draggable-grab grabbing style will not be applied if the user clicked on a button or a link within the draggable.
https://jira.dti.ulaval.ca/browse/MODUL-231
- draggable-grab will now be more user friendly interacting with a nested button / link

draggable-grab with nested buttons and links

---

package-lock.json
package.json

Release 1.0.0-beta.39
Revert broken package-lock.json
https://jira.dti.ulaval.ca/projects/MODUL/versions/24798

release 1.0.0-beta.39

---

src/components/file-upload/__snapshots__/file-upload.spec.ts.snap
src/components/file-upload/file-upload.html
src/components/file-upload/file-upload.ts

-- Add display: flex on footer to stretch button height when a file is added
-- https://jira.dti.ulaval.ca/browse/MODUL-230
-- https://jira.dti.ulaval.ca/browse/ENA2-1018

MODUL-230 - ENA2-1018 - Les boutons devraient avoir la même hauteur

---

src/components/input-style/input-style.scss
src/components/textfield/textfield.ts
src/directives/textarea-auto-height/textarea-auto-height.ts
src/mixins/input-management/input-management.ts

- Le visuel des champs ne s'affichent plus avec les bonne couleurs lorsqu'il est en erreur et en état focus.
- Lorsque copie colle du texte dans textfield avec la prop word-wrap, les retours de ligne ne sont pas effacés.
- L'étiquette des champs ne s'affiche pas au bon endroit lorsque le prop tag-style est utilisée.
- https://jira.dti.ulaval.ca/browse/MODUL-238
- https://jira.dti.ulaval.ca/browse/ENA2-1813

MODUL-238 - Problème d'affichage dans le textfield et dans le textarea

---

src/directives/draggable/draggable-allow-scroll.ts
src/directives/scroll-to/scroll-to-lib.ts

Enable bottom autoscroll when dragging an element.
https://jira.dti.ulaval.ca/browse/MODUL-241

Enable bottom autoscroll when dragging

---

package-lock.json
package.json

Release 1.0.0-beta.40
https://jira.dti.ulaval.ca/projects/MODUL/versions/24888

Release/1.0.0 beta.40

---

src/components/icon-button/icon-button.ts

Erreur lors du refactor des noms d'icônes.
[MODUL-272](https://jira.dti.ulaval.ca/browse/MODUL-272)

Fix icon-name prop typo in m-icon-button

---

package-lock.json
package.json

release 1.0.0-beta.41
https://jira.dti.ulaval.ca/projects/MODUL/versions/24988

Release/1.0.0 beta.41

---

src/components/edit-window/edit-window.scss

-- Add position relative to the edit-window__body
-- https://jira.dti.ulaval.ca/browse/MODUL-274

MODUL-274 - ENA2-1771

---

src/components/message/message.scss

Gérer la largeur du composant m-message lorsqu’un mot est trop long
- https://jira.dti.ulaval.ca/browse/MODUL-278
- https://jira.dti.ulaval.ca/browse/ENA2-1382

MODUL-278: Gérer la largeur du composant m-message lorsqu’un mot est trop long

---

src/components/file-select/file-select.ts

https://jira.dti.ulaval.ca/browse/MODUL-282

MODUL-282 - ajouter getter hasLabel dans m-file-select

---

src/assets/icons/sprites-default.svg

Ajout nouvelle icône de mauvaise réponse.
[MODUL-275](https://jira.dti.ulaval.ca/browse/MODUL-275)

Add wrong-anwser icon

---

package.json

Add npm scripts to echo the current version of the package.json so a CI tool (Jenkins for instance) will be able to tag the master branch and then publish the package to npm.
part of : https://jira.dti.ulaval.ca/browse/MODUL-106

add print version scripts for automation

---

src/components/error-template/error-template.ts
src/components/textfield/textfield.ts

Fix invalid plugin usage
- textfield: useless button plugin installation
- error-template: services should be installed independently from components
https://jira.dti.ulaval.ca/browse/MODUL-300

fix invalid plugin installation

---

src/components/modal/modal.html

- [ x] Provide a small description of the changes introduced by this PR
AEL need to have bold part of the text in the $confirm service. Which use the modal window
MODUL-292
- [ x] Include this section in the release notes
Modal now support html tags

Allow modal windows to have html tag

---

package-lock.json
package.json

Release 1.0.0-beta.42 -- DO NOT SQUASH MERGE
https://jira.dti.ulaval.ca/projects/MODUL/versions/25080

Release v1.0.0-beta.42

---

package-lock.json
package.json

release 1.0.0-beta.43
https://jira.dti.ulaval.ca/projects/MODUL/versions/25195

Release v1.0.0-beta.43

---

doc/gitflow.md

not ready yet for review
https://jira.dti.ulaval.ca/browse/MODUL-271

Fix gitflow documentation

---

src/components/edit-window/edit-window.sandbox.html
src/components/edit-window/edit-window.sandbox.ts
src/sandbox/index.ts
src/styles/abstracts/_mixins.scss
tests/app/meta-init.ts

Change the padding on mobile for all popup.
Enable edit-window sandbox in modul-component.
https://jira.dti.ulaval.ca/browse/MODUL-309
https://jira.dti.ulaval.ca/browse/P411-905

MODUL-309 - modifier le padding des popup pour ENA2-1914

---

src/components/carousel/carousel.html
src/components/carousel/carousel.ts

Add click and tap event in m-carousel
[MODUL-322](https://jira.dti.ulaval.ca/browse/MODUL-322)

Add click and tap event in m-carousel

---

src/components/accordion-group/__snapshots__/accordion-group.spec.ts.snap
src/components/accordion-group/accordion-group.sandbox.html
src/components/accordion/__snapshots__/accordion.spec.ts.snap
src/components/accordion/accordion.html
src/components/accordion/accordion.sandbox.html
src/components/accordion/accordion.scss
src/components/accordion/accordion.spec.ts
src/components/accordion/accordion.ts
src/components/checkbox/__snapshots__/checkbox.spec.ts.snap
src/components/checkbox/checkbox.html
src/components/component-names.ts
src/components/error-message/__snapshots__/error-message.spec.ts.snap
src/components/index.ts
src/components/plus/__snapshots__/plus.spec.ts.snap
src/components/plus/plus.html
src/components/plus/plus.sandbox.html
src/components/plus/plus.sandbox.ts
src/components/plus/plus.scss
src/components/plus/plus.spec.ts
src/components/plus/plus.ts
src/sandbox/index.ts
tests/app/meta-init.ts

- Création du nouveau composant **m-plus**
- Ménage dans les composants **m-accordion** et **m-accordion-group** suite à l'intégration du nouveau composant.
- Ajouter de sandbox pour les composants **m-plus**, **m-accordion** et **m-accordion-group**
- https://jira.dti.ulaval.ca/browse/MODUL-286
- https://jira.dti.ulaval.ca/browse/ENA2-2116
- https://jira.dti.ulaval.ca/browse/ENA2-1706
http://feature-modul-286-new-component-m-plus-modul-dv.paas.exp.ulaval.ca/m-plus

m-plus component - for merging

---

src/components/dialog/dialog.html
src/components/dialog/dialog.sandbox.html

Update the svg close name 
[MODUL-329](https://jira.dti.ulaval.ca/browse/MODUL-329)

Update the svg close name

---

src/components/carousel/carousel.html
src/components/carousel/carousel.ts

Enlever un click inutile
[MODUL-331](https://jira.dti.ulaval.ca/browse/MODUL-331)

Remove useless click event

---

src/components/file-upload/file-upload.html
src/components/file-upload/file-upload.lang.en.json
src/components/file-upload/file-upload.lang.fr.json
src/components/file-upload/file-upload.spec.ts
src/components/file-upload/file-upload.ts
src/filters/filesize/filesize.lang.en.json
src/filters/filesize/filesize.lang.fr.json
src/filters/filesize/filesize.spec.ts
src/filters/filesize/filesize.ts
src/filters/filter-names.ts
src/lang/fr.ts
src/utils/file/file.ts

Make public filesize filter (f-m-filesize) which was internal to m-fileupload.
Make public extractExtension which was internal to FileService ($file)
https://jira.dti.ulaval.ca/browse/MODUL-339
Make public filesize filter (f-m-filesize) which was internal to m-fileupload.
Make public extractExtension which was internal to FileService ($file)

Make public filesize filter and file extension extractor

---

src/assets/icons/sprites-default.svg

Added "download" and "replace" icons.
https://jira.dti.ulaval.ca/browse/MODUL-344

MODUL-344 - Add icons

---

src/directives/draggable/draggable.ts
src/directives/user-select/remove-user-select.ts

Fixes drag and drop on PC with touchscreen
https://jira.dti.ulaval.ca/browse/MODUL-345

fix mouse dnd with chrome on MS Surface

---

src/components/navbar-item/navbar-item.ts

itemEl.style in m-navbar-item is undefined
https://jira.dti.ulaval.ca/browse/MODUL-342

MODUL-342 - itemEl.style in m-navbar-item is undefined

---

package-lock.json
package.json

Merge back branch release/v1.0.0-beta.46 into develop. MERGE COMMIT ONLY - DO NOT SQUASH/REBASE MERGE.

Release/v1.0.0 beta.47

---

src/components/error-template/error-template.html
src/components/error-template/error-template.scss
src/components/error-template/error-template.ts

Utiliser v-html pour titre message erreur, changer font-weight et centrer texte si aucune lien/stack sous une erreur 
https://jira.dti.ulaval.ca/browse/MODUL-354

ENA2-354 - changer font-weight titre, centrer texte, v-html

---

src/components/error-access-denied/error-access-denied.lang.fr.json
src/components/error-browser-not-supported/error-browser-not-supported.lang.fr.json
src/components/error-config-not-supported/error-config-not-supported.lang.fr.json
src/components/error-cookies-not-supported/error-cookies-not-supported.lang.fr.json
src/components/error-page-not-found/error-page-not-found.lang.fr.json
src/components/error-technical-difficulty/error-technical-difficulty.lang.fr.json

Mise à jour des messages d'erreur. 
À noter : 
- Pour error-config-not-supported.lang.fr la clé hint.secondary a été ajoutée.
- Pour m-error-technical-difficulty la clé help a été supprimée.
https://jira.dti.ulaval.ca/browse/MODUL-353

Mise à jour des messages suite à la révision d'Audrey

---

src/components/tree-icon/tree-icon.scss
src/components/tree-node/__snapshots__/tree-node.spec.ts.snap
src/components/tree-node/tree-node.html
src/components/tree-node/tree-node.scss
src/components/tree-node/tree-node.spec.ts
src/components/tree-node/tree-node.ts

Many visual improvements.
https://jira.dti.ulaval.ca/browse/MODUL-350

MODUL-350 - tree improvements

---

src/components/carousel-item/carousel-item.html
src/components/carousel-item/carousel-item.scss
src/components/carousel-item/carousel-item.ts
src/components/carousel/carousel.html
src/components/carousel/carousel.sandbox.html
src/components/carousel/carousel.sandbox.ts
src/components/carousel/carousel.scss
src/components/carousel/carousel.ts

Amélioration de la navigation en mobile, ajout des aperçus gauche et droite.
[MODUL-287](https://jira.dti.ulaval.ca/browse/MODUL-287)

Amélioration de la navigation du carousel mobile

---

src/components/rich-text-editor/adapter/vue-froala.ts
src/utils/clean/htmlClean.ts

corrects a bug when pasting a link in the rich text editor
https://jira.dti.ulaval.ca/browse/MODUL-359

corrected bug

---

doc/jenkins-release-pipeline.groovy

jenkins release script email on completion

---

.github/CODEOWNERS
package-lock.json

- package-lock.json has bunch of Maven references which are not allowed in Github project
- npm audit fix
- add codeowners to ensure package*.json files are not accidentally changed

Bugfix Jenkins compilation fail

---

src/components/rich-text-editor/adapter/vue-froala.ts

filter div tags when pasting in the RTE
https://jira.dti.ulaval.ca/browse/MODUL-373

filter divs

---

src/mixins/portal/portal.ts

Rendre plus safe le destroy car le portal EL peut avoir disparu (combinaison weird de slot/if)
- [ X] Include links to issues
https://jira.dti.ulaval.ca/browse/MODUL-385

Be safer when removing portal target EL

---

src/assets/icons/sprites-default.svg
src/components/menu-item/menu-item.scss
src/components/menu/menu.sandbox.html

… remplacer icone profil, ajustement du label du menu-item
- Ajouter l'icône maison
- Remplacer l'icône de profil
- Ajuster le positionnement du texte dans le menu-item
- https://jira.dti.ulaval.ca/browse/MODUL-391
- https://jira.dti.ulaval.ca/browse/ENA2-1384

MODUL-391 - Ajustement du visuel du menu pour le menu-utilisateur

---

src/components/rich-text-editor/rich-text-editor.scss

set the RTE "mobile contextual menu padding" on focus only
https://jira.dti.ulaval.ca/browse/MODUL-387

set the "contextual menu padding" on focus only

---

src/components/menu-item/menu-item.ts

MODUL-394 - ajout evenement click sur menu-item

---

src/utils/modal/alert.ts
src/utils/modal/confirm.ts

/MODUL-392_confirm: nexttick
/MODUL-392_confirm: nexttick
$confirm et $alert attendent le prochain cycle avant de "résolver"
https://jira.dti.ulaval.ca/browse/MODUL-392

/MODUL-392_confirm: nexttick

---

src/components/navbar-item/navbar-item.scss

The separator between items was almost invisible when the content was on one line.
https://jira.dti.ulaval.ca/browse/MODUL-264
https://jira.dti.ulaval.ca/browse/P411-982

ENA2-1481 - fix sub-nav skin bug

---

src/components/progress/progress.sandbox.html
src/components/progress/progress.sandbox.ts

add dynamic examples of progress component
https://jira.dti.ulaval.ca/browse/MODUL-372
https://jira.dti.ulaval.ca/browse/ENA2-2145

MODUL-372 - add dynamic examples of progress component

---

src/components/link/link.sandbox.html
src/styles/utils/_link.scss
src/styles/utils/_utils.scss

Ajouter une classe utilitaire pour les liens
- https://jira.dti.ulaval.ca/browse/MODUL-362
- https://jira.dti.ulaval.ca/browse/ENA2-1927

MODUL-362 - Ajouter des classes utilitaires pour les liens

---

src/directives/draggable/draggable.spec.ts
src/directives/draggable/draggable.ts
src/utils/selection/selection.ts

Improve draggable reliability after opening the contextuel menu
https://jira.dti.ulaval.ca/browse/MODUL-366
- Improve draggable reliability after opening the contextuel menu

Improve draggable reliability after opening the contextuel menu

---

src/components/rich-text-editor/adapter/vue-froala.scss

When creating a link in the RTE, the checkbox "check" icon is not displayed correctly
https://jira.dti.ulaval.ca/browse/MODUL-389
https://jira.dti.ulaval.ca/browse/MODUL-393

RTE Fix create link checkbox position

---

src/components/rich-text-editor/rich-text-editor.sandbox.html
src/components/rich-text-editor/rich-text-editor.spec.ts
src/components/rich-text-editor/rich-text-editor.ts

you can give a selector to the toolbar-sticky-offset prop
https://jira.dti.ulaval.ca/browse/MODUL-388
https://jira.dti.ulaval.ca/browse/MODUL-390

calculate ToolbarStickyOffset

---

src/utils/modul/modul.ts

Fix an error when closing popup
https://jira.dti.ulaval.ca/browse/MODUL-405

Fix an error when closing popup

---

src/components/navbar-item/navbar-item.scss

Lorsqu'il y a un seul item de sélectionner dans le navbar avec le skin main, center la ligne jaune
https://jira.dti.ulaval.ca/browse/MODUL-411

MODUL-411 - Lorsqu'il y a un seul item de sélectionné dans le navbar avec le skin main, center la ligne jaune

---

src/components/navbar/navbar.ts

J'ai fait les changements proposés par @jfnadeau dans le billet lié d'ENA2 selon ce que je comprenais de son commentaire, mais je n'ai pu reproduire le bug moi même.
https://jira.dti.ulaval.ca/browse/MODUL-410
https://jira.dti.ulaval.ca/browse/ENA2-2508

MODUL-410 - ENA2-2508

---

src/components/rich-text-editor/rich-text-editor.ts

correctes a bug with the scrollable-container 
https://jira.dti.ulaval.ca/browse/MODUL-407

do not test if the container exists

---

src/components/error-template/error-template.html

Modifier le titre du template des messages erreurs pour un v-html pour que le balisage des message erreurs soient pris en compte (  <br> ).
https://jira.dti.ulaval.ca/browse/MODUL-414

MODUL-414 - Modifier le h1 du error-template pour un v-html

---

src/components/limit-text/limit-text.ts

corrects an error : TypeError: Cannot read property 'innerHTML' of undefined
https://jira.dti.ulaval.ca/browse/MODUL-400

corrected "property of undefined" bug

---

src/mixins/input-state/input-state.ts

getInputs will sometime return undefined and it is normal.
https://jira.dti.ulaval.ca/browse/MODUL-408

don't throw exception when input state can't get it's input

---

src/components/carousel/carousel.sandbox.html
src/components/carousel/carousel.scss

Bogue carrousel, marge par défaut webkit ul
[MODUL-413](https://jira.dti.ulaval.ca/browse/MODUL-413)

Bogue carrousel, marge par défaut webkit ul

---

src/components/tree-node/tree-node.scss

Displays hierarchical lines for root level of tree component.
https://jira.dti.ulaval.ca/browse/MODUL-399

display hierarchical lines for root level

---

src/components/dialog/dialog.sandbox.html
src/components/dialog/dialog.scss
src/components/edit-window/edit-window.scss
src/components/modal/modal.html
src/components/modal/modal.sandbox.html
src/components/modal/modal.scss
src/components/modal/modal.ts
src/styles/abstracts/_mixins.scss

- Modifier le padding dans m-dialog, m-modal, m-edit-window
- Ajouter un prop width au m-modal
- https://jira.dti.ulaval.ca/browse/MODUL-376

MODUL-376 - Ajuster le padding dans les fenêtres

---

src/components/file-upload/file-upload.spec.ts
src/components/file-upload/file-upload.ts

https://jira.dti.ulaval.ca/browse/MODUL-412

MODUL-412 - correction validation parametres fichiers televerses

---

src/components/rich-text-editor/adapter/vue-froala.ts

correct the bug "Cannot read property 'style' of null"
https://jira.dti.ulaval.ca/browse/MODUL-419

m-rich-text-editor : VueFroala - CueFroannot read property 'style' of null 

---

src/directives/draggable/draggable-allow-scroll.ts

use element height as the threshold in v-m-draggable-allow-scroll directive
https://jira.dti.ulaval.ca/browse/MODUL-418

use element height as the threshold

---

src/components/menu/menu-skins.scss
src/components/menu/menu.html
src/components/navbar/navbar.scss
src/styles/abstracts/_var-color.scss

La couleur doit menu principal (premier niveau) doit être la suivante: #2e2e2e
Cette couleur doit être ajoutée dans MODUL
- https://jira.dti.ulaval.ca/browse/MODUL-429
- https://jira.dti.ulaval.ca/browse/ENA2-2692

MODUL-429 - Ajouter une nouvelle teinte de gris et changer la couleur du navbar

---

src/assets/icons/svg/m-svg__message-rocket.svg

add a new svg to modUL
https://jira.dti.ulaval.ca/browse/MODUL-430

add new svg

---

src/components/rich-text-editor/adapter/vue-froala.ts

stops loosing focus when clicking on the RTE label
https://jira.dti.ulaval.ca/browse/MODUL-427

do not loose focus on label click

---

src/directives/badge/badge.ts

Régler un problème de propriété non définie sur l'élément html dans edge
https://jira.dti.ulaval.ca/browse/MODUL-424
https://jira.dti.ulaval.ca/browse/ENA2-2396

MODUL-424 - regler probleme de propriete undefined dans edge

---

src/components/limit-text/limit-text.html
src/components/limit-text/limit-text.sandbox.html
src/components/limit-text/limit-text.sandbox.ts
src/components/limit-text/limit-text.ts

Add v-html support for limit-text component
https://jira.dti.ulaval.ca/browse/MODUL-425
https://jira.dti.ulaval.ca/browse/P411-1001

Feature/modul_425 - add v-html support for limit-text component

---

src/filters/filesize/filesize.ts

Method fileSize is now exported to use directly in typescript files.
https://jira.dti.ulaval.ca/browse/MODUL-456

export fileSize method

---

src/components/carousel-item/carousel-item.html
src/components/carousel-item/carousel-item.scss
src/components/carousel-item/carousel-item.ts
src/components/carousel/carousel.sandbox.html

Enlever transition sur initiation du carousel
[MODUL-453](https://jira.dti.ulaval.ca/browse/MODUL-453)

Enlever transition sur initiation du carousel

---

src/components/edit-window/edit-window.scss
src/styles/abstracts/_mixins.scss

Fixed missing padding-bottom in edit-window component on Mac with Firefox/Safari.
https://jira.dti.ulaval.ca/browse/MODUL-457

added m-fixed-box-padding mixin

---

src/components/limit-text/limit-text.scss

Enlever marge sur texte original
[MODUL-452](https://jira.dti.ulaval.ca/browse/MODUL-452)

Enlever la marge du RTE dans le limit-text sur un texte qui ne dépasse pas la limite

---

src/components/dropdown/dropdown.spec.ts
src/components/error-browser-not-supported/error-browser-not-supported.spec.ts
src/components/inplace-edit/inplace-edit.spec.ts
src/components/limit-text/limit-text.spec.ts
src/mixins/media-queries/media-queries.ts
src/utils/media-queries/media-queries.ts
tests/helpers/mock.ts

MediaQueries is now less ressource intensive
https://jira.dti.ulaval.ca/browse/MODUL-450
https://jira.dti.ulaval.ca/browse/MODUL-443

Improve media queries perf

---

src/components/tooltip/tooltip.sandbox.html
src/components/tooltip/tooltip.scss

Force the line break when the content is to long and have no space. 
[MODUL-467](https://jira.dti.ulaval.ca/browse/MODUL-467)

Infobulle - Force the line break

---

src/components/datepicker/__snapshots__/datepicker.spec.ts.snap
src/components/timepicker/__snapshots__/timepicker.spec.ts.snap
src/components/validation-message/__snapshots__/validation-message.spec.ts.snap
src/components/validation-message/validation-message.html
src/components/validation-message/validation-message.sandbox.html

Permettre l'italique dans les messages d'erreur du textfield
https://jira.dti.ulaval.ca/browse/MODUL-454
https://jira.dti.ulaval.ca/browse/ENA2-2245

Bugfix/modul-454 Permettre l'italique dans les messages d'erreur du textfield

---

package-lock.json
src/directives/draggable/draggable.spec.ts
src/directives/draggable/draggable.ts
src/utils/polyfills.ts

During a drag and drop, the cursor was positioned on the top left corner of the drag image. It's now centered in the middle of it.
https://jira.dti.ulaval.ca/browse/MODUL-433
https://jira.dti.ulaval.ca/browse/ENA2-2338

MODUL-433 - D&D - Centrer le dragimage (carré vert) sous le curseur lors du drag

---

src/components/dialog/dialog.sandbox.html
src/components/dialog/dialog.scss
src/components/edit-window/edit-window.sandbox.html
src/components/edit-window/edit-window.scss

Fixed scrolling problems in modal windows on iPhone. Scrolling is now always "momentum-based".
https://jira.dti.ulaval.ca/browse/MODUL-459

fix scrolling in modal windows on iPhone

---

src/mixins/element-queries/element-queries.ts

Reduce layout trashing in element-queries
https://jira.dti.ulaval.ca/browse/MODUL-477

MODUL-477 reduce layout trashing in element-queries

---

src/directives/draggable/draggable.ts
src/directives/droppable/droppable.ts
src/utils/event/event.ts

fix a bug that caused webpack4 not to work for brio
https://jira.dti.ulaval.ca/browse/MODUL-479

fix a bug that caused webpack4 not to work for brio

---

src/components/error-access-denied/error-access-denied.lang.fr.json
src/components/error-config-not-supported/error-config-not-supported.lang.fr.json

Changer deux libellés dans les pages d'erreur
ENA2-3063

modifier les libellés de deux conseils dans les pages d'erreur

---

src/components/rich-text-editor/adapter/vue-froala.ts
src/components/rich-text-editor/rich-text-editor.html
src/components/rich-text-editor/rich-text-editor.lang.en.json
src/components/rich-text-editor/rich-text-editor.lang.fr.json
src/components/rich-text-editor/rich-text-editor.spec.ts
src/components/rich-text-editor/rich-text-editor.ts

As requested the field label was to be changed to be "URL ou courriel" instead of "URL". 
https://jira.dti.ulaval.ca/browse/MODUL-483

Changed URL field label when adding a link

---

src/meta/v2/meta-v2.ts
tests/meta-v2/generate-meta.ts

Ajout de la version du package.json pour l'afficher dans website
https://jira.dti.ulaval.ca/browse/MODUL-507

Afficher version en cours modul dans website

---

src/components/dialog/dialog.lang.fr.json

Ajustement au libellé.
https://jira.dti.ulaval.ca/browse/MODUL-481

MODUL-481 Corriger le libellé du tooltip

---

src/components/input-style/input-style.scss
src/components/textarea/textarea.sandbox.html
src/components/textfield/textfield.sandbox.html

Update required fields styles
https://jira.dti.ulaval.ca/browse/ENA2-875
https://jira.dti.ulaval.ca/browse/MODUL-503

MODUL-503 - Update required fields styles

---

tests/app/navigation/navigation.html

fixed little bug in sandbox navigation page

fix problem with scroll to top in sandbox

---

src/components/file-upload/file-upload.html
src/components/file-upload/file-upload.ts
src/mixins/portal/portal.ts

Fix loading error when opening the file-upload
https://jira.dti.ulaval.ca/browse/MODUL-517

Fix loading error when opening the file-upload

---

src/components/dropdown/dropdown.html
src/components/dropdown/dropdown.sandbox.ts
src/components/dropdown/dropdown.ts
src/components/popup/popup.html
src/components/popup/popup.ts
src/mixins/portal/portal.ts

Selection in the dropdown was broken since the introduction of lazy portals.
https://jira.dti.ulaval.ca/browse/MODUL-520

repair dropdown selection

---

.github/CODEOWNERS

Change the list of codeowners.

codeowners change

---

src/components/file-upload/file-upload.lang.en.json
src/components/file-upload/file-upload.lang.fr.json
src/components/file-upload/file-upload.spec.ts

Un autre changement dans les libellés dans le composant du file-upload.
https://jira.dti.ulaval.ca/browse/MODUL-519
https://jira.dti.ulaval.ca/browse/ENA2-3083

MODUL-519 - Changer libellés

---

src/components/rich-text-editor/rich-text-editor.ts

Changed the labels 'insert' in rich text editor
https://jira.dti.ulaval.ca/browse/MODUL-524
https://jira.dti.ulaval.ca/browse/ENA2-2580

MODUL-524 - RTE -  Adapted the labels ‘Insert’

---

src/components/rich-text-editor/rich-text-editor.sandbox.html

2 RTE ne chargent plus dans le sandbox
https://jira.dti.ulaval.ca/browse/MODUL-531

Fixed sandbox RTE not working

---

src/components/modal/modal.lang.fr.json

Changer le texte "Fermer la fenêtre" pour garder seulement "Fermer"
[MODUL-529](https://jira.dti.ulaval.ca/browse/MODUL-529)

Changer le texte du bouton fermer de la modal

---

src/components/rich-text-editor/adapter/vue-froala.html
src/components/rich-text-editor/adapter/vue-froala.scss
src/components/rich-text-editor/adapter/vue-froala.ts
src/components/rich-text-editor/rich-text-editor.html
src/components/rich-text-editor/rich-text-editor.sandbox.html
src/components/rich-text-editor/rich-text-editor.sandbox.ts
src/components/textfield/textfield.sandbox.html

input-style readonly prop and the RTE now work together
https://jira.dti.ulaval.ca/browse/MODUL-544

make rte work with input-style readonly property

---

src/components/panel/panel.sandbox.html
src/components/panel/panel.scss

Ajustement du padding dans le m-panel
https://jira.dti.ulaval.ca/browse/MODUL-541

MODUL-541: Ajustement du visuel de composant m-panel pour l'admission

---

src/components/rich-text-editor/adapter/vue-froala.ts

RTE simulateReadOnlyBlur would throw error when combiner with an uninitialized rich-text
https://jira.dti.ulaval.ca/browse/MODUL-550

RTE fix Cannot read property 'edit' of undefined

---

src/directives/scroll-to/scroll-to.sandbox.html
src/directives/scroll-to/scroll-to.sandbox.ts
src/utils/scroll-to/scroll-to.ts

there where a problem in scroll position calculation when item was at the bottom of the page causing animation to appear linear instead of slowing to the target
https://jira.dti.ulaval.ca/browse/MODUL-548

fix problem in animation when scroll to bottom of the page

---

.htmlhintrc
.vscode/extensions.json
.vscode/settings.json

Changed Settings.json and added html hint plugin to add html formmating options to align with Brio standards
https://jira.dti.ulaval.ca/projects/MODUL/issues/MODUL-553

fix settings and add html extension setting

---

src/components/navbar-item/navbar-item.scss
src/components/navbar/navbar.sandbox.html
src/components/navbar/navbar.scss

Add basic styles to plain skin to improve styling by parent component
https://jira.dti.ulaval.ca/browse/MODUL-552
https://jira.dti.ulaval.ca/browse/ENA2-3500

MODUL-552 - add basic styles to plain skin

---

src/components/rich-text-editor/adapter/vue-froala.html
src/components/rich-text-editor/adapter/vue-froala.spec.ts
src/components/rich-text-editor/adapter/vue-froala.ts
src/components/rich-text-editor/rich-text-editor-options.ts
src/components/rich-text-editor/rich-text-editor.sandbox.html
src/components/rich-text-editor/rich-text-editor.sandbox.ts

Rewrite RTE model management to make it simpler and avoid issues
https://jira.dti.ulaval.ca/browse/MODUL-551
https://jira.dti.ulaval.ca/browse/ENA2-3475

Rework RTE model handling to make it more simple.

---

README.md

Add a getting started section to the readme . It will be removed from website
https://jira.dti.ulaval.ca/browse/MODUL-536

Modul 536 Add getting started to readme

---

src/mixins/portal/portal.ts

EdgeHTML 17 semble avoir un problème avec le position absolute sans préciser de top / left. Pas certain pourquoi il s'agit dune régression dans beta-66
https://jira.dti.ulaval.ca/browse/MODUL-569?filter=29451

fix problem in edgeHTML 17 with modal

---

.vscode/extensions.json
.vscode/settings.json
README.md
conf/tslint.json
src/utils/index.ts

minor modification to add tslint autofix on save + added a scss extension in the suggested list

Added auto tslint fix on save + scss as a vscode extension

---

src/components/dropdown/__snapshots__/dropdown.spec.ts.snap
src/components/dropdown/dropdown.spec.ts
src/components/tooltip/__snapshots__/tooltip.spec.ts.snap
src/components/tooltip/tooltip.html

Fix snapshot generation under node 10.12.0

Fix jest snapshot generation under node 10.12.0

---

src/utils/http/http.ts

When there is already informations in Headers, they were lost when the new Headers was create. 
We now check if there is already a Headers, if so the info is add to it. Otherwise a Headers is create with the info.
https://jira.dti.ulaval.ca/browse/MODUL-197

MODUL-197 Ajout d'information au header

---

src/components/checkbox/checkbox.sandbox.html
src/components/checkbox/checkbox.sandbox.ts
src/components/checkbox/checkbox.scss

Lorsque le checkbox est désactivé et coché, le crochet n'est pas visible.
https://jira.dti.ulaval.ca/browse/MODUL-559

MODUL-559 Afficher crochet dans le checkbox lorsque disabled

---

src/components/navbar-item/navbar-item.scss

Inverse les couleurs de background et d'hover du skin tab-light à la demande de MH
https://jira.dti.ulaval.ca/browse/MODUL-552
https://jira.dti.ulaval.ca/browse/ENA2-3500

MODUL-552 change color of navbar tab-light skin

---

src/components/table/table.scss

Added hover effect on table body rows.
https://jira.dti.ulaval.ca/browse/MODUL-568

MODUL-568 - Add table body row hover effect

---

src/directives/draggable/draggable.ts
src/directives/sortable/sortable.sandbox.html
src/directives/sortable/sortable.sandbox.ts
src/directives/sortable/sortable.scss
src/directives/sortable/sortable.ts

Add sandbox to m-sortable directive
https://jira.dti.ulaval.ca/browse/MODUL-584

MODUL-584 - Add sandbox to m-sortable directive

---

src/components/checkbox/__snapshots__/checkbox.spec.ts.snap
src/components/checkbox/checkbox.html
src/components/checkbox/checkbox.sandbox.html
src/components/checkbox/checkbox.sandbox.ts
src/components/checkbox/checkbox.scss
src/components/checkbox/checkbox.spec.ts
src/components/checkbox/checkbox.ts
src/mixins/input-state/input-state.ts

Le composant checkbox supporte maintenant le readonly
https://jira.dti.ulaval.ca/browse/MODUL-570
MCheckbox supporte la prop "readonly"

MODUL-570 m-checkbox readonly

---

.github/CODEOWNERS

modify codeowner

---

src/components/rich-text-editor/adapter/vue-froala.html
src/components/rich-text-editor/adapter/vue-froala.scss
src/components/rich-text-editor/adapter/vue-froala.ts
src/components/rich-text-editor/rich-text-editor.sandbox.html

Fix disabling the editor (text would disappear when toggling the property)
https://jira.dti.ulaval.ca/browse/ENA2-3606
https://jira.dti.ulaval.ca/browse/MODUL-586

fix disabling the rich-text

---

src/components/switch/switch.scss

Add fix to position right not working in switch component. CSS class change name missing when developer change wrap to body name class
https://jira.dti.ulaval.ca/browse/MODUL-601

MODUL-601 - add fix to position right not working in switch component

---

src/components/component-names.ts
src/components/components-plugin.ts
src/components/show-more/__snapshots__/show-more.spec.ts.snap
src/components/show-more/show-more.html
src/components/show-more/show-more.lang.en.json
src/components/show-more/show-more.lang.fr.json
src/components/show-more/show-more.sandbox.html
src/components/show-more/show-more.sandbox.ts
src/components/show-more/show-more.scss
src/components/show-more/show-more.spec.ts
src/components/show-more/show-more.ts
src/lang/fr.ts

Added m-show-more component.
https://jira.dti.ulaval.ca/browse/MODUL-588

add m-show-more component

---

src/components/limit-text/limit-text.sandbox.html
src/components/limit-text/limit-text.sandbox.ts
src/components/limit-text/limit-text.ts

MODUL-620 - Fixed bug from content reduction regex

---

src/components/scroll-top/scroll-top.sandbox.scss

fix compilation problem because of a merge
https://jira.dti.ulaval.ca/browse/MODUL-639

fix merge problem

---

.github/CODEOWNERS

Ajout Vincent Guillemet au code owner du projet pour les code reviews

Ajout Vincent comme code owner

---

src/components/textfield/textfield.html
src/components/textfield/textfield.ts

Add emit search on key enter in textfield type search
https://jira.dti.ulaval.ca/browse/MODUL-646

MODUL-646 - Add emit search on key enter in textfield type search

---

package-lock.json
package.json
src/components/rich-text-editor/rich-text-editor-options.ts

Rich-text: fixed regressions caused by version 2.9.1
https://jira.dti.ulaval.ca/browse/MODUL-649
https://jira.dti.ulaval.ca/browse/ENA2-3673
Bumped froala to v2.9.1

Bump froala version to 2.9.1 and fix a regression caused by it

---

.npmrc
package-lock.json

Remove Maven entries from package-lock.json
https://jira.dti.ulaval.ca/browse/MODUL-660

MODUL-660 - remove maven entries

---

src/utils/i18n/i18n.spec.ts
src/utils/i18n/i18n.ts

When using special chars in translation string, an exception is thrown.
https://jira.dti.ulaval.ca/browse/MODUL-662

fixed how string parameters are compiled with special chars

---

.npmrc

.npmrc make publishing impossible.

removed npmrc

---

.npmrc

Reverts ulaval/modul-components#664

Revert "removed npmrc"

---

src/components/login/__snapshots__/login.spec.ts.snap
src/components/textfield/__snapshots__/textfield.spec.ts.snap
src/components/textfield/textfield.html

Remove a test button that was acciendtally left in.
A "TEST" button was added to all textfields
https://jira.dti.ulaval.ca/browse/MODUL-666

Removed test button

---

src/styles/base/_base.scss

fix IE11 font issue
https://jira.dti.ulaval.ca/browse/MODUL-677

MODUL-677 - fix IE11 font issue

---

src/components/calendar/calendar.sandbox.ts

small fix for calendar sandbox

fix calendar sandbox

---

src/components/progress/__snapshots__/progress.spec.ts.snap
src/components/progress/progress.html
src/components/progress/progress.sandbox.html
src/components/progress/progress.scss
src/components/progress/progress.spec.ts
src/components/progress/progress.ts

Added monochrome skin on m-progress.
https://jira.dti.ulaval.ca/browse/MODUL-671

MODUL-671 - added monochrome skin

---

src/components/table/table.scss

Added font-weight style for th tags in m-table.
https://jira.dti.ulaval.ca/browse/MODUL-672

MODUL-672 - added font-weight style fot th tags

---

src/components/input-style/input-style.scss
src/components/textfield/textfield.sandbox.html
src/components/textfield/textfield.spec.ts
src/components/textfield/textfield.ts

Add to textfield the number type
[MODUL-697](https://jira.dti.ulaval.ca/browse/MODUL-697)

MODUL-697 - Add input type number

---

src/components/tooltip/tooltip.scss

Suite à une suggestion de JP Marois. Ajout du légère bordure sur le tooltip en mode Link.
https://jira.dti.ulaval.ca/browse/MODUL-702

MODUL-702 - Add light border on link mode

---

src/components/rich-text-editor/adapter/vue-froala.scss

Force disabled color in rich-text-editor
[MODUL-703](https://jira.dti.ulaval.ca/browse/MODUL-703)

MODUL-703 - Force disabled color in rich-text-editor

---

src/components/show-more/show-more.sandbox.ts
src/components/show-more/show-more.ts

show-more plugin modularisation

fix show more plugin

---

src/components/accordion-group/__snapshots__/accordion-group.spec.ts.snap
src/components/error-message/__snapshots__/error-message.spec.ts.snap
src/components/link/__snapshots__/link.spec.ts.snap
src/components/link/link.ts
src/components/page-not-found/__snapshots__/page-not-found.spec.ts.snap
src/components/session-expired/__snapshots__/session-expired.spec.ts.snap

Modification de la valeur par défaut du tabindex du composant m-link
https://jira.dti.ulaval.ca/browse/MODUL-679

Changed default tabindex

---

src/components/navbar/__snapshots__/navbar.spec.ts.snap
src/components/navbar/navbar.html

Suppression du aria-hidden dans le menu et déplacement du role menubar
https://jira.dti.ulaval.ca/browse/MODUL-682
https://jira.dti.ulaval.ca/browse/ENA2-2773

Aria-hidden deleted and role menubar moved

---

src/components/table/table.sandbox.html
src/components/table/table.sandbox.ts
src/components/table/table.scss

Reverted table-layout: fixed; width: 100%; word-wrap: break-word.
https://jira.dti.ulaval.ca/browse/MODUL-718

revert table-layout fixed, width 100%, word-wrap break-word

---

src/components/checkbox/checkbox.scss
src/components/tree/__snapshots__/tree.spec.ts.snap
src/components/tree/tree-node/__snapshots__/tree-node.spec.ts.snap
src/components/tree/tree-node/tree-node.html
src/components/tree/tree.html
src/components/tree/tree.scss
src/styles/mixins/_button.scss

Changed cursor for pointer on multiple-node-checkbox when disabled
https://jira.dti.ulaval.ca/browse/MODUL-627

MODUL-627 - Cursor pointer on multiple-node-checkbox disabled

---

src/components/popper/popper.ts

MODUL-725 - Added property modifis.hide.enable=false in popper.js

---

src/components/form/form-field.ts
src/components/form/form.sandbox.html
src/components/form/form.sandbox.ts

maj du form sandbox
https://jira.dti.ulaval.ca/browse/MODUL-732?jql=text%20~%20%22sandbox%20form%22

MODUL-732 - mise à jour du form sandbox

---

src/utils/form/form-field/form-field.ts

Voir explication dans le ticket jira
https://jira.dti.ulaval.ca/browse/MODUL-735

MODUL-735 - gerer les changes sur les types object pour form field

---

src/components/tooltip/tooltip.html
src/components/tooltip/tooltip.sandbox.html
src/components/tooltip/tooltip.scss
src/components/tooltip/tooltip.ts

Ajout de la prop 'size' permettant de changer la largeur du tooltip. Valeurs permises 'small' et 'large'
https://jira.dti.ulaval.ca/browse/MODUL-739

MODUL-739 MTooltip Prop Size

---

src/components/tree/__snapshots__/tree.spec.ts.snap
src/components/tree/tree-node/__snapshots__/tree-node.spec.ts.snap
src/components/tree/tree-node/tree-node.html
src/components/tree/tree-node/tree-node.scss
src/components/tree/tree-node/tree-node.spec.ts
src/components/tree/tree-node/tree-node.ts
src/components/tree/tree.html
src/components/tree/tree.sandbox.html
src/components/tree/tree.spec.ts
src/components/tree/tree.ts

Add readonly mode in m-tree
[MODUL-734](https://jira.dti.ulaval.ca/browse/MODUL-734)

MODUL-734 - Add readonly mode to the m-tree

---

src/components/toast/toast.scss

Add a simple animation
https://jira.dti.ulaval.ca/browse/MODUL-653

MODUL-653 - toast animation

---

src/components/progress/progress.scss

Changed colors of m-progress monochrome skin.
https://jira.dti.ulaval.ca/browse/MODUL-726

MODUL-726 - m-progress change colors of monochrome skin

---

src/components/file-select/file-select.html

* self close input
Correction de syntaxe

fix some linter warning

---

src/components/form/form-field.ts
src/components/rich-text-editor/adapter/vue-froala.ts
src/components/rich-text-editor/rich-text-editor.sandbox.ts
src/components/rich-text-editor/rich-text-editor.ts
tsconfig.json

Hotfix pour 81 et fix tsconfig pour plus que ce genre d'import arrive

removed baseurl in tsconfig.json and fixed bad import

---

src/components/rich-text-editor/adapter/vue-froala.ts

Bug fix : cursor returns at start position after inserting special characters.
https://jira.dti.ulaval.ca/browse/MODUL-757

MODUL-757 - vue-froala : bug fix

---

src/components/components-plugin.ts

Add daterangepicker to components-plugin for use in brio

Add daterangepicker to components-plugin

---

src/components/datepicker/datepicker.sandbox.html
src/components/option/option.sandbox.html
src/components/popper/popper.sandbox.html
src/components/popper/popper.ts
src/components/tooltip/tooltip.sandbox.html

MODUL-748 - fixed popper limit in viewport

---

src/components/button/button.sandbox.html
src/components/button/button.sandbox.ts
src/utils/enums/enums.ts

Add enum utils to get enum as an array of value
Add dynamic properties in button sandbox
Add enum utils to get enum as an array of values
https://jira.dti.ulaval.ca/browse/MODUL-656
https://jira.dti.ulaval.ca/browse/MODUL-652

MODUL-652 - Add dynamic properties in button sandbox

---

src/directives/scroll-to/scroll-to.sandbox.ts
src/utils/scroll-to/scroll-to-service.sandbox.html
src/utils/scroll-to/scroll-to-service.sandbox.ts
src/utils/scroll-to/scroll-to.ts

Add instant scrollTo (no animation time)
https://jira.dti.ulaval.ca/browse/MODUL-664

MODUL-664 - Add instant scroll to

---

src/directives/drag-and-drop/draggable/draggable.spec.ts
src/directives/drag-and-drop/droppable/droppable.spec.ts
src/directives/sortable/sortable.spec.ts

Repair sortable tests

---

src/components/rich-text-editor/adapter/vue-froala.scss

fix padding issues
https://jira.dti.ulaval.ca/browse/MODUL-760

MODUL-760 - fix rich-text-editor padding issues

---

src/components/rich-text-editor/adapter/vue-froala.ts
src/components/rich-text-editor/rich-text-editor.sandbox.html
src/components/rich-text-editor/rich-text-editor.sandbox.ts

Fixed a bug when clicking on a rich text editor previously disabled caused editor to be closed.
https://jira.dti.ulaval.ca/browse/MODUL-764

MODUL-764 - vue-froala : focus fix

---

src/components/rich-text/rich-text.sandbox.html
src/components/rich-text/rich-text.scss

Added max-width on images inside m-rich-text.
https://jira.dti.ulaval.ca/browse/MODUL-758

MODUL-758 - m-rich-text : added max-width for images

---

src/components/show-more/show-more.html
src/components/show-more/show-more.sandbox.html
src/components/show-more/show-more.sandbox.ts
src/components/show-more/show-more.ts

Added skin prop on m-show-more component to be able to use the monochrome skin of m-progress.
https://jira.dti.ulaval.ca/browse/MODUL-756

MODUL-756 - m-show-more : added skin prop

---

.circleci/config.yml
.travis.yml
Jenkinsfile
README.md
package.json

Deux modifications dans ce PR.
1. J'ai changé la commande `npm install` par `npm ci `pour honoré le package-lock.json
2. J'ai enlevé le step redondant` npm pack` du build pour gagner environ 30% du temps de build
MODUL-746

Speed up ci build

---

src/components/rich-text-editor/rich-text-editor.sandbox.html

MODUL-783 - Updated sandbox

---

src/components/form/__snapshots__/form.spec.ts.snap

fix snapshot test

---

conf/webpack.config.js

Quick fix pour la performance du webpack-dev-server

remove async false in webpack config

---

src/assets/icons/sprites-default.svg
src/components/message-page/message-page.sandbox.html
src/components/message-page/message-page.ts
src/components/message/message.ts

Ajout et utilisation de 4 icônes avec fond blanc pour message d'erreur dans m-message et m-message-page.
https://jira.dti.ulaval.ca/browse/MODUL-799

MODUL-799 - Nouveaux icônes avec fond blanc

---

package-lock.json
package.json
src/components/input-mask/input-mask.html
src/components/input-mask/input-mask.sandbox.html
src/components/input-mask/input-mask.sandbox.ts
src/components/input-mask/input-mask.ts

input-mask sera une sous-composante (non exposé hors Modul) pour la création de nouvelle composante qui ont besoin de masquer la saisit de l'utilisateur a l'intérieur d'un champs texte.
MODUL-794

Modul 794 mise en place sous composante input mask 

---

package-lock.json
src/components/calendar/__snapshots__/calendar.spec.ts.snap
src/components/dropdown/__snapshots__/dropdown.spec.ts.snap

fix snapshot

---

src/components/calendar/__snapshots__/calendar.spec.ts.snap

fix unit test

---

.github/CODEOWNERS

changed fro Frederic Duguay as code owned

change modul code owner

---

src/components/calendar/calendar.spec.ts

jai du mettre un test a ignore a cause du build qui fail (voir note dans le code)

Fix unit test in calendar prise 2

---

src/components/rich-text-editor/adapter/vue-froala.scss
src/components/rich-text-editor/adapter/vue-froala.ts

- Correction de plusieurs problèmes de focus et d'activation du RTE
https://jira.dti.ulaval.ca/browse/MODUL-795
https://jira.dti.ulaval.ca/browse/ENA2-5113

MODUL-795 - resoudre probleme de focus dans texte riche

---

src/components/option/option-item/option-item.html
src/components/option/option-item/option-item.scss

Augmentation de la taille des icônes à 20px dans le menu option
https://jira.dti.ulaval.ca/browse/MODUL-805

MODUL-805 - Increasing icons to 20px

---

src/components/calendar/__snapshots__/calendar.spec.ts.snap
src/components/form/form.sandbox.html
src/components/form/form.sandbox.ts
src/utils/form/form.spec.ts
src/utils/form/form.ts

Ajouter, enlever des champs après la création du formulaire.
https://jira.dti.ulaval.ca/browse/MODUL-817

MODUL-817 - Ajouter et retirer des champs au formulaire après sa création

---

src/components/datepicker/__snapshots__/datepicker.spec.ts.snap
src/components/error-message/__snapshots__/error-message.spec.ts.snap
src/components/icon-button/__snapshots__/icon-button.spec.ts.snap
src/components/icon/__snapshots__/icon.spec.ts.snap
src/components/icon/icon.ts
src/components/list-item/__snapshots__/list-item.spec.ts.snap
src/components/message/__snapshots__/message.spec.ts.snap
src/components/page-not-found/__snapshots__/page-not-found.spec.ts.snap
src/components/session-expired/__snapshots__/session-expired.spec.ts.snap
src/components/timepicker/__snapshots__/timepicker.spec.ts.snap
src/components/validation-message/__snapshots__/validation-message.spec.ts.snap

Valeur par défaut du m-icon chande à 20px au lieu de 1em
https://jira.dti.ulaval.ca/browse/MODUL-812

MODUL-812 - Changed default size of m-icon and update snapshots

---

src/filters/date/date.sandbox.html
src/filters/date/date.sandbox.ts
src/filters/date/date/date.ts
src/filters/date/period/period.spec.ts
src/filters/date/period/period.ts

Remove fullmode for period (not useful)
Fix 1er when in the same month
Add cases in period sandbox
https://jira.dti.ulaval.ca/browse/MODUL-776
Remove fullmode on period filter as it is not useful.

MODUL-776 - Fix 1er, remove full mode, add cases in sandbox

---

src/components/daterangepicker/daterangepicker.ts

Fix daterangepicker labels initialization.  It was not standard (compared to the rest of the code) and it caused issues in brio
https://jira.dti.ulaval.ca/browse/MODUL-815

Fix daterangepicker labels initialization

---

package-lock.json
package.json
src/components/dropdown/__snapshots__/dropdown.spec.ts.snap

Update Froala npm package  version 2.9.1 to 2.9.3 to correct issues where some formatted text would sometimes wrongfully create links (without URLs).
https://jira.dti.ulaval.ca/browse/MODUL-822
https://jira.dti.ulaval.ca/browse/ENA2-3155

MODUL-822 - Update Froala version to 2.9.3

---

src/components/character-count/__snapshots__/character-count.spec.ts.snap
src/components/character-count/character-count.html
src/components/character-count/character-count.scss

Bold sur le nombre de caractères saisi au lieu de sur le total
https://jira.dti.ulaval.ca/browse/MODUL-811

MODUL-811 - Bold inverted in character-count

---

src/components/integerfield/integerfield.sandbox.html
src/components/integerfield/integerfield.sandbox.ts
src/components/integerfield/integerfield.ts
src/components/moneyfield/moneyfield.html
src/components/moneyfield/moneyfield.ts
src/utils/money/money.ts

Étant donner que money est un simple wrapper du decimal field jai simplifier un peu .

moneyfield

---

package-lock.json
package.json

Move devDependency 'qs' to dependency. If not, http service is not working and remote project need to install de dependency to fix the problem.
https://jira.dti.ulaval.ca/browse/MODUL-843

MODUL-843 - move devDependency 'qs' to dependency

---

src/components/popup/popup.html

Ajouter dans le template du popup.html la prop class-name
https://jira.dti.ulaval.ca/browse/MODUL-847 
https://jira.dti.ulaval.ca/browse/AEL-418

MODUL-847: Ajouter dans le template du popup.html la prop class-name

---

src/components/integerfield/integerfield.html
src/components/integerfield/integerfield.ts

Lors du click sur le "Enter", le message d'erreur ci-dessous apparaît.
Property or method "onEnter" is not defined on the instance but referenced during render.
https://jira.dti.ulaval.ca/browse/MODUL-840

MODUL-840 - Fix onEnter event

---

tsconfig.lib.json

fix storie in distribution

---

src/components/integerfield/integerfield.sandbox.html
src/components/integerfield/integerfield.sandbox.ts
src/components/integerfield/integerfield.ts
src/components/moneyfield/moneyfield.html
src/components/moneyfield/moneyfield.sandbox.html
src/components/moneyfield/moneyfield.sandbox.ts
src/components/moneyfield/moneyfield.ts

moneyfield with an initial provided value doesn't display it's value
Errors / messages can't be displayed
https://jira.dti.ulaval.ca/browse/MODUL-854

MODUL-854 - fix moneyfield initialization

---

package-lock.json
src/components/form/form-field.spec.ts
src/components/form/form-field.ts
src/components/form/form.sandbox.html
src/components/form/form.sandbox.ts
src/utils/form/form-field/form-field.spec.ts
src/utils/form/form-field/form-field.ts
src/utils/form/form.spec.ts
src/utils/form/form.ts

Tel que discuté avec @jipigi  et JP Marois. Le but est d'avoir un UX optimisé et d'uniformiser le comportement de certain types de champs dans un formulaire.
https://jira.dti.ulaval.ca/browse/MODUL-844
https://wiki.dti.ulaval.ca/pages/viewpage.action?spaceKey=MODUL&title=Gestion+des+erreurs
Breaking change: l'option "message after touch ne fait plus parti de l'interface FormFieldOptions. Elle doit simplement être enlevé si utilisé.

MODUL-844 - Nouveau processus de validation de champs de formulaire

---

.vscode/settings.json
conf/storybook/addons.ts
conf/storybook/config.jest.ts
conf/storybook/config.ts
conf/storybook/manager-head.html
conf/storybook/modul-theme.ts
conf/storybook/modulTheme.js
conf/storybook/webpack.config.js
package-lock.json
package.json
src/components/button/__snapshots__/button.stories.ts.snap
src/components/button/button.stories.ts

- theming storybook
- fix required context pour loader les stories dans jest
- ajout addon knobs  (https://github.com/storybooks/storybook/tree/master/addons/knobs)
- ajout addons source (https://github.com/storybooks/storybook/tree/master/addons/storysource)
https://jira.dti.ulaval.ca/browse/MODUL-830

MODUL-830/Storybook improvement

---

src/utils/scroll-to/scroll-to-service.sandbox.html
src/utils/scroll-to/scroll-to.ts

MODUL-876 - Add ScrollDuration.Fast

---

src/components/accordion/accordion.scss
src/components/error-pages/error-technical-difficulty/error-technical-difficulty.sandbox.html
src/components/message-page/message-page.scss

Ajout d'un width large dans le sandbox pour l'affichage des modales des erreurs techniques
https://jira.dti.ulaval.ca/browse/MODUL-870

MODUL-870 - width large added on sandbox

---

src/components/datepicker/__snapshots__/datepicker.spec.ts.snap
src/components/input-style/__snapshots__/input-style.spec.ts.snap
src/components/input-style/__snapshots__/input-style.stories.ts.snap
src/components/input-style/input-style.html
src/components/input-style/input-style.scss
src/components/input-style/input-style.stories.ts
src/components/input-style/input-style.ts
src/components/integerfield/__snapshots__/integerfield.spec.ts.snap
src/components/moneyfield/__snapshots__/moneyfield.spec.ts.snap
src/components/rich-text-editor/__snapshots__/rich-text-editor.spec.ts.snap
src/components/textarea/__snapshots__/textarea.spec.ts.snap
src/components/textfield/__snapshots__/textfield.spec.ts.snap
src/components/textfield/textfield.sandbox.html
src/components/timepicker/__snapshots__/timepicker.spec.ts.snap

Améliorer le balisage du composant m-input-style.
Retirer le margin-top lorsqu'il n'y a pas de label sur le composant m-input-style
https://jira.dti.ulaval.ca/browse/MODUL-863

MODUL-863: Retirer le margin-top lorsqu'il n'y a pas de label sur le composant m-input-style

---

src/components/autocomplete/autocomplete.html
src/components/dropdown/dropdown.ts

Dans un dropdown filtrable, si on entre du texte et qu'on sort du dropdown, le filtre courant sera toujours appliqué lors de la ré-ouverture de ce dernier. 
https://jira.dti.ulaval.ca/browse/MODUL-858
https://jira.dti.ulaval.ca/browse/ENA2-5218
Je crois que cela va également régler: 
https://jira.dti.ulaval.ca/browse/ENA2-5200

MODUL-858 - Correction filtre dropdown

---

src/components/autocomplete/__snapshots__/autocomplete.spec.ts.snap
src/components/autocomplete/autocomplete.html
src/components/autocomplete/autocomplete.sandbox.html
src/components/autocomplete/autocomplete.sandbox.ts
src/components/autocomplete/autocomplete.ts
src/components/dropdown/dropdown.html
src/components/dropdown/dropdown.ts

* En sortant du champ de la recherche, accepter la valeur saisie à la main, si elle correspond a une des valeurs dans la liste d'autosuggest. Le comportement actuel de la composante supprime la valeur, si elle n'a pas été sélectionnée dans la liste, même si elle est identique à la valeur dans la liste.
* Permettre un template html custom pour les items de résultats
* Ajouter max-length au champ quand c'est filtrable
https://jira.dti.ulaval.ca/browse/MODUL-865

MODUL-865 - Autocomplete enhancements

---

src/utils/http/http.ts

Axios request config is now returned as a promise in the request interceptor. This allows the HttpPluginOptions authorization function to be a promise as well. Projects can then always send a valid authorization token into the http header instead of adding complexity of checking token expiration before making a secure http call, etc. For example, the authorization function can 'wait' for an expired token to be refreshed before being added to the header.
https://jira.dti.ulaval.ca/browse/MODUL-891

MODUL-891 - HttpPluginOptions allows Promise for authorization function

---

src/components/rich-text-editor/adapter/vue-froala.ts
src/components/rich-text-editor/rich-text-editor.sandbox.html
src/components/rich-text-editor/rich-text-editor.sandbox.ts

Inserting image in RTE on a page with multiple RTEs caused the image to be inserted in the last RTE instance.
https://jira.dti.ulaval.ca/browse/MODUL-905

MODUL-905 - RTE image insertion bugfix

---

src/utils/modul-date/modul-date.spec.ts
src/utils/modul-date/modul-date.ts

Dates were compared after converting them into UTC(0) timezone. That caused problems when comparing dates from another timezone. Example, 2019-03-29 23:59:59 would become 2019-03-30 3:59:59.
https://jira.dti.ulaval.ca/browse/MODUL-867

MODUL-867 - timezone conversion bugfix

---

src/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
src/components/accordion-group/accordion-group.html
src/components/accordion-group/accordion-group.scss
src/components/accordion-group/accordion-group.stories.ts
src/components/accordion-group/accordion-group.ts

Add some feature to accordion-group
[MODUL-888](https://jira.dti.ulaval.ca/browse/MODUL-888)

MODUL-888 - Add slot to accordion-group

---

package-lock.json
src/components/component-names.ts
src/components/decimalfield/__snapshots__/decimal.stories.ts.snap
src/components/decimalfield/decimal.stories.ts
src/components/decimalfield/decimalfield.html
src/components/decimalfield/decimalfield.scss
src/components/decimalfield/decimalfield.spec.ts
src/components/decimalfield/decimalfield.ts
src/components/input-mask/input-mask.ts
src/components/integerfield/integerfield.ts
src/components/moneyfield/__snapshots__/moneyfield.spec.ts.snap
src/components/moneyfield/moneyfield.html
src/components/moneyfield/moneyfield.ts
src/utils/l10n/l10n.ts

Mettre le decimal field dans le money field
Add a decimalfield which manage basic localization (english and french)
Use decimalfield in moneyfield
https://jira.dti.ulaval.ca/browse/MODUL-892

Implémentation de base d'un decimal-field

---

src/components/periodpicker/periodpicker.spec.ts
src/components/periodpicker/periodpicker.ts

WIP periodepicker to work with date

---

conf/storybook/sandboxes.storybook.ts
conf/storybook/styles/storybook.scss

fix margin in storybook

---

src/components/autocomplete/__snapshots__/autocomplete.spec.ts.snap
src/components/autocomplete/autocomplete.html
src/components/autocomplete/autocomplete.ts
src/components/dropdown/dropdown.html

Ajout de l'atribut autocomplete
[MODUL-919](https://jira.dti.ulaval.ca/browse/MODUL-919)

MODUL-919 - Ajout de l'autocomplesion sur autocomplete

---

src/components/autocomplete/autocomplete.ts

La valeur du input doit être réinitialisé avec le model
[MODUL-921](https://jira.dti.ulaval.ca/browse/MODUL-921)

MODUL-921 - Bogue affichage 'Aucun résultat'

---

src/components/checkbox/checkbox.html
src/components/dropdown/__snapshots__/dropdown.spec.ts.snap
src/components/dropdown/dropdown.html
src/components/modal/modal.sandbox.html
src/components/overlay/overlay.sandbox.html
src/components/periodpicker/periodpicker.sandbox.html
src/components/radio/radio.html
src/components/rich-text-editor/rich-text-editor.sandbox.html
src/components/switch/switch.html
src/components/validation-message/validation-message.sandbox.html

Changer grosseur icône liste déroulante
[MODUL-922](https://jira.dti.ulaval.ca/browse/MODUL-922)

MODUL-922 - Changer grosseur icône liste déroulante

---

src/components/decimalfield/__snapshots__/decimal.stories.ts.snap
src/components/decimalfield/decimal.stories.ts
src/components/decimalfield/decimalfield.ts
src/components/moneyfield/__snapshots__/moneyfield.stories.ts.snap
src/components/moneyfield/moneyfield.html
src/components/moneyfield/moneyfield.sandbox.html
src/components/moneyfield/moneyfield.stories.ts
src/components/moneyfield/moneyfield.ts
src/components/textfield/textfield.sandbox.html

Ajouter une limite dans le moneyfield. Cette limite est traitée dans le decimalfield.
https://jira.dti.ulaval.ca/browse/MODUL-927
https://jira.dti.ulaval.ca/browse/ENA2-5666

MODUL-967 - Limit in moneyfield and decimalfield

---

src/components/decimalfield/decimalfield.ts

Decimal field rounding property was incorrectly initialized which resulted in a console error
https://jira.dti.ulaval.ca/browse/MODUL-936

fix rounding prop initialization in decimalfield

---

src/components/input-mask/input-mask.ts

fix a probleme where the cleave.js typing that was exported by the input-mask component.

fixed typing problem in cleave.js

---

src/components/table/table.ts

Erreur de ma part en refactorisant les colonnes du table, cette proriété semble avoir pris le bord
https://jira.dti.ulaval.ca/browse/MODUL-947

MODUL-947 - centered property on column table

---

conf/storybook/webpack.config.js
conf/webpack.config.js

stylelint and tslint was not running during the storybook process, there were added to the webpack configuration

added linter to storybook configuration

---

src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
src/components/decimalfield/__snapshots__/decimal.stories.ts.snap
src/components/input-style/__snapshots__/input-style.stories.ts.snap
src/components/input-style/input-style.ts
src/components/integerfield/__snapshots__/integerfield.spec.ts.snap
src/components/moneyfield/__snapshots__/moneyfield.spec.ts.snap
src/components/periodpicker/__snapshots__/periodpicker.stories.ts.snap
src/components/rich-text-editor/__snapshots__/rich-text-editor.spec.ts.snap
src/components/textarea/__snapshots__/textarea.spec.ts.snap
src/components/textfield/__snapshots__/textfield.spec.ts.snap
src/components/timepicker/__snapshots__/timepicker.stories.ts.snap
src/components/timepicker/timepicker.html
src/components/timepicker/timepicker.stories.ts
src/components/timepicker/timepicker.ts

Fix a bug where values in the popup weren't reset to the model after closing the popup
Fix timepicker label
https://jira.dti.ulaval.ca/browse/MODUL-945

timepicker popup model update

---

src/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
src/components/error-pages/error-technical-difficulty/error-technical-difficulty.stories.ts

MODUL-953 -  Add stories for error-page-technical-difficulty
https://jira.dti.ulaval.ca/browse/MODUL-953

MODUL-953 -  Add stories for error-page-technical-difficulty

---

src/components/error-pages/error-page-not-found/__snapshots__/error-page-not-found.stories.ts.snap
src/components/error-pages/error-page-not-found/error-page-not-found.stories.ts
src/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
src/components/error-pages/error-technical-difficulty/error-technical-difficulty.stories.ts

Add the Error Page component (Page not found) in storybook.
https://jira.dti.ulaval.ca/browse/MODUL-952

Add the Error Page component (Page not found) in storybook

---

src/components/error-pages/error-cookies-not-supported/__snapshots__/error-cookies-not-supported.stories.ts.snap
src/components/error-pages/error-cookies-not-supported/error-cookies-not-supported.stories.ts
src/components/error-pages/error-page-not-found/__snapshots__/error-page-not-found.stories.ts.snap
src/components/error-pages/error-page-not-found/error-page-not-found.stories.ts
src/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
src/components/error-pages/error-technical-difficulty/error-technical-difficulty.stories.ts

Add the Error Page component (Cookies not supported) in storybook
https://jira.dti.ulaval.ca/browse/MODUL-951

Add the Error Page component (Cookies not supported) in storybook

---

src/components/error-pages/error-config-not-supported/__snapshots__/error-config-not-supported.stories.ts.snap
src/components/error-pages/error-config-not-supported/error-config-not-supported.stories.ts
src/components/error-pages/error-cookies-not-supported/__snapshots__/error-cookies-not-supported.stories.ts.snap
src/components/error-pages/error-cookies-not-supported/error-cookies-not-supported.stories.ts
src/components/error-pages/error-page-not-found/__snapshots__/error-page-not-found.stories.ts.snap
src/components/error-pages/error-page-not-found/error-page-not-found.stories.ts
src/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
src/components/error-pages/error-technical-difficulty/error-technical-difficulty.stories.ts

Add the Error Page component (Config not supported) in storybook.
https://jira.dti.ulaval.ca/browse/MODUL-950

Add the Error Page component (Config not supported) in storybook

---

src/components/checkbox/checkbox.ts

https://jira.dti.ulaval.ca/browse/MODUL-964

MODUL-964 - Force value change when checkbox is indeterminate (edge bug)

---

src/styles/mixins/_froala.scss
src/styles/utils/_link.scss

Links inside RTE now have same look as m-link.
https://jira.dti.ulaval.ca/browse/MODUL-956

Feature/modul 956 - RTE links style

---

src/components/input-style/input-style.scss

Styles (couleur et marge) sur le affixes
https://jira.dti.ulaval.ca/browse/MODUL-935

MODUL-935 - Added styles for moneyfield affixe

---

src/components/component-names.ts
src/components/repeater/__snapshots__/repeater.stories.ts.snap
src/components/repeater/repeater.html
src/components/repeater/repeater.lang.en.json
src/components/repeater/repeater.lang.fr.json
src/components/repeater/repeater.scss
src/components/repeater/repeater.spec.ts
src/components/repeater/repeater.stories.ts
src/components/repeater/repeater.ts
src/lang/en.ts
src/lang/fr.ts

Add a basic implementation for repeater component
https://jira.dti.ulaval.ca/browse/MODUL-929

repeater base implementation

---

.vscode/settings.json

J'ai remarqué que certain developpeur n'avais pas ce setting par défault.

add single quote for import setting

---

src/components/decimalfield/decimal.stories.ts
src/components/decimalfield/decimalfield.ts
src/components/input-mask/input-mask.ts
src/components/moneyfield/__snapshots__/moneyfield.stories.ts.snap
src/components/moneyfield/moneyfield.html
src/components/moneyfield/moneyfield.stories.ts

Improve moneyfield precision handling
See linked issue for more detail
https://jira.dti.ulaval.ca/browse/MODUL-928

Improve moneyfield precision display

---

src/components/autocomplete/autocomplete.html
src/components/autocomplete/autocomplete.sandbox.html
src/components/autocomplete/autocomplete.ts
src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
src/components/datepicker/datepicker.html
src/components/datepicker/datepicker.stories.ts
src/components/decimalfield/__snapshots__/decimalfield.stories.ts.snap
src/components/decimalfield/decimalfield.html
src/components/decimalfield/decimalfield.stories.ts
src/components/dropdown/__snapshots__/dropdown.stories.ts.snap
src/components/dropdown/dropdown.html
src/components/dropdown/dropdown.stories.ts
src/components/input-style/input-style.ts
src/components/integerfield/integerfield.html
src/components/integerfield/integerfield.sandbox.html
src/components/textarea/textarea.html
src/components/textarea/textarea.sandbox.html
src/components/textfield/__snapshots__/textfield.stories.ts.snap
src/components/textfield/textfield.html
src/components/textfield/textfield.stories.ts
src/components/timepicker/__snapshots__/timepicker.stories.ts.snap
src/components/timepicker/timepicker.html
src/components/timepicker/timepicker.stories.ts
src/mixins/input-management/input-management.ts

Avoir l'option de mettre toujours le label dans le haut
[MODUL-974](https://jira.dti.ulaval.ca/browse/MODUL-974)

MODUL-974 - Avoir l'option de mettre toujours le label dans le haut

---

src/components/rich-text-editor/adapter/vue-froala.ts

RTE now closes on mouseup instead of mousedown.
https://jira.dti.ulaval.ca/browse/MODUL-966

MODUL-966 - RTE close fix

---

src/components/integerfield/integerfield.sandbox.ts
src/components/integerfield/integerfield.ts
src/components/textfield/__snapshots__/textfield.stories.ts.snap
src/components/textfield/textfield.stories.ts
src/mixins/input-management/input-management.spec.ts
src/mixins/input-management/input-management.ts

Proposition pour régler  #919 . Fix dans intergerfield + support du comportement avec trimWordWrap (ceci devrait être déplacer du InputManagement vers le textfield selon moi) + Creation d'un test unitaire pour le InputManagement 
https://jira.dti.ulaval.ca/browse/MODUL-942
Input-management mixins was modified (all modul form input) To fix a issues with v-model update submission when model is updated by parent components. This changes can affect form validation so full testing of form in projet should be performed to ensure no regressions.

Fix double emit input management prise #2

---

src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
src/components/decimalfield/__snapshots__/decimal.stories.ts.snap
src/components/input-style/__snapshots__/input-style.spec.ts.snap
src/components/input-style/__snapshots__/input-style.stories.ts.snap
src/components/input-style/input-style.html
src/components/input-style/input-style.scss
src/components/integerfield/__snapshots__/integerfield.spec.ts.snap
src/components/moneyfield/__snapshots__/moneyfield.spec.ts.snap
src/components/rich-text-editor/__snapshots__/rich-text-editor.spec.ts.snap
src/components/textarea/__snapshots__/textarea.spec.ts.snap
src/components/textfield/__snapshots__/textfield.stories.ts.snap
src/components/textfield/textfield.stories.ts
src/components/timepicker/__snapshots__/timepicker.stories.ts.snap

fix misalignment between labeled and not labeled  fields
https://jira.dti.ulaval.ca/browse/MODUL-977
https://jira.dti.ulaval.ca/browse/MODUL-939
https://jira.dti.ulaval.ca/browse/MODUL-978

MODUL-977 - fix misalignment between labeled and not labeled  fields

---

package.json
src/components/datepicker/datepicker.ts
src/components/form/__snapshots__/form.stories.ts.snap
src/components/form/control-directive.ts
src/components/form/fallouts/built-in-form-action-fallouts.ts
src/components/form/form.html
src/components/form/form.sandbox.html
src/components/form/form.stories.ts
src/components/form/form.ts
src/components/message/message.ts
src/utils/form/abstract-control.ts

- Changement de la directive pour ecouter les event focus et blur du vue au lieu de ceux html natif
- Enelever rxjs pour une solution plus simpliste
- Ajout du toast dans le template pour etre reactif
- Enlever automatiquement le toast et le summary losqu'il plus d'erreur
https://jira.dti.ulaval.ca/browse/MODUL-1003

MODUL-1003 / Amelioration directive intergration avec composantes modul

---

src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
src/components/datepicker/datepicker.stories.ts
src/components/datepicker/datepicker.ts

Added a prop to skip all validaiton in datepicker . we can now use custom validator instead of built in format and min max validator
https://jira.dti.ulaval.ca/browse/MODUL-982

MODUL-982 - added prop 'skipInputValidation' to skip input validation in datepicker

---

src/components/overlay/overlay.html
src/components/overlay/overlay.sandbox.html
src/components/overlay/overlay.sandbox.ts
src/components/overlay/overlay.ts

Ajout du mode waiting pour changer l'état du bouton lorsqu'un appel back-end est en court
[MODUL-1020](https://jira.dti.ulaval.ca/browse/MODUL-1020)

MODUL-1020 - Ajout du mode waiting sur le m-overlay

---

src/filters/date/date.sandbox.html
src/filters/date/date.sandbox.ts
src/filters/date/period/period.spec.ts
src/filters/date/period/period.ts

Add param to formatPeriod to add oportunity to add short month date filter to the period format
https://jira.dti.ulaval.ca/browse/MODUL-1012

MODUL-1012 - add param to periodFormat to pass shortMonth true

---

src/components/limit-text/limit-text.sandbox.html
src/components/limit-text/limit-text.ts

Ajout d'un espace insécable avant closing tag du m-limit-text
[MODUL-1006](https://jira.dti.ulaval.ca/browse/MODUL-1006)

MODUL-1006 - Ajout d'un espace insécable avant closing tag du m-limit-text

---

src/components/table/__snapshots__/table.spec.ts.snap
src/components/table/__snapshots__/table.stories.ts.snap
src/components/table/table.html
src/components/table/table.lang.en.json
src/components/table/table.lang.fr.json
src/components/table/table.scss
src/components/table/table.stories.ts
src/components/table/table.ts

* Ajouter un état aux colonnes triables d'un tableau
* Ajouter un attribut title sur le bouton de tri
https://jira.dti.ulaval.ca/browse/MODUL-994
https://jira.dti.ulaval.ca/browse/MPOPO-696

MODUL-994: Ajouter un état aux colonnes triables d'un tableau

---

src/components/moneyfield/__snapshots__/moneyfield.stories.ts.snap
src/components/moneyfield/moneyfield.stories.ts
src/filters/money/money.sandbox.ts
src/filters/money/money.spec.ts
src/filters/money/money.ts

If the flag is active
12.00 becomes 12
1.02 becomes 1.02 (same as before)
1.20 becomes 1.20 (same as before)
https://jira.dti.ulaval.ca/browse/MODUL-1004

CurrencyFormat: Add the possibility to hide decimal 0s

---

src/components/form/__snapshots__/form.stories.ts.snap
src/components/form/form.stories.ts
src/utils/form/validators/email/email.spec.ts
src/utils/form/validators/email/email.ts
src/utils/form/validators/max-length/max-length.spec.ts
src/utils/form/validators/min-length/min-length.spec.ts
src/utils/form/validators/min-length/min-length.ts
src/utils/form/validators/required/required.spec.ts

Validator for email , minlength and maxlength should allow empty value. 
https://jira.dti.ulaval.ca/browse/MODUL-1038
If you use the EmailValidator MaxLengthValidator or MinLengthValidator on a required field, then you should also add the RequiredValidator to ensure correct validations.

MODUL-1038 - Allow empty value for email min and max validator

---

.github/CODEOWNERS

add @guignol1981  as code owner for everything about m-form

Add guignol1981 as codeowner for form

---

src/filters/date/date.sandbox.html
src/filters/date/date/date.ts

* Add showDay option to date filter
https://jira.dti.ulaval.ca/browse/MODUL-1064

MODUL-1064: Ajouter des options au filtre de date

---

src/components/integerfield/__snapshots__/integerfield.spec.ts.snap
src/components/integerfield/integerfield.html
src/components/moneyfield/__snapshots__/moneyfield.stories.ts.snap
src/components/moneyfield/moneyfield.stories.ts

…e .scss
fix mismatch between css classes used by the html and the .scss
https://jira.dti.ulaval.ca/browse/MODUL-1065

MODUL-1065 - Le integerfield ne s'affiche pas comme les autres fields

---

src/components/form/__snapshots__/form.stories.ts.snap
src/components/form/form.stories.ts
src/utils/form/control-options.ts
src/utils/form/form-control.ts
src/utils/form/validators/max/max.spec.ts
src/utils/form/validators/min/min.spec.ts

Adds reactivity to initialValue by providing a function
https://jira.dti.ulaval.ca/browse/MODUL-1068

MODUL-1068 - Add reactivity to initial value

---

src/components/form/form.stories.ts
src/utils/form/validators/date-format/date-format.spec.ts
src/utils/form/validators/date-format/date-format.ts

remove length validation in dateformat, use min length validator for this,

Fix date format validator

---

src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
src/components/datepicker/datepicker.stories.ts

Simply add a storybook with big and max limit datepicker
https://jira.dti.ulaval.ca/browse/MODUL-1082

MODUL-1082 - Add a new storybook for datepicker

---

src/components/chip/__snapshots__/chip.stories.ts.snap
src/components/chip/chip-add/__snapshots__/chip-add.spec.ts.snap
src/components/chip/chip-add/__snapshots__/chip-add.stories.ts.snap
src/components/chip/chip-add/chip-add.html
src/components/chip/chip-delete/__snapshots__/chip-delete.spec.ts.snap
src/components/chip/chip-delete/__snapshots__/chip-delete.stories.ts.snap
src/components/chip/chip-delete/chip-delete.html

Quand on click sur une chip dans un formulaire, elle provoque le submit du form.
https://jira.dti.ulaval.ca/browse/MODUL-1073

MODUL-1073 - explicit type button

---

src/components/component-names.ts
src/components/components-plugin.ts
src/components/expandable-layout/__snapshots__/expandable-layout.stories.ts.snap
src/components/expandable-layout/expandable-layout.html
src/components/expandable-layout/expandable-layout.scss
src/components/expandable-layout/expandable-layout.stories.ts
src/components/expandable-layout/expandable-layout.ts

Added m-expandable-layout component that can be used to add an expandable panel next to some content.
https://jira.dti.ulaval.ca/browse/MODUL-1055

MODUL-1055 - added expandable-layout component

---

src/assets/icons/sprites-default.svg

Added 2 arrow button icons.
https://jira.dti.ulaval.ca/browse/MODUL-1077

MODUL-1077 - added arrow button icons

---

src/components/expandable-layout/expandable-layout.stories.ts
src/components/expandable-layout/expandable-layout.ts

Added panelScrollMode prop and MExpandableLayoutPanelScrollMode enum. Mode prop and MExpandableLayoutMode enum are now deprecated.
https://jira.dti.ulaval.ca/browse/MODUL-1084

MODUL-1084 - m-expendable-layout : rename mode prop

---

src/components/expandable-layout/__snapshots__/expandable-layout.stories.ts.snap
src/components/expandable-layout/expandable-layout.scss
src/components/expandable-layout/expandable-layout.stories.ts

Changed the scrollbar style of panel for the more compact one. Also updated the background colors in storybook.
https://jira.dti.ulaval.ca/browse/MODUL-1083

MODUL-1083 - changed scrollbar style

---

src/components/component-names.ts
src/components/phonefield/__snapshots__/phonefield.stories.ts.snap
src/components/phonefield/phonefield.html
src/components/phonefield/phonefield.scss
src/components/phonefield/phonefield.ts
src/components/select/__snapshots__/select.stories.ts.snap
src/components/select/select-item/select-item.html
src/components/select/select-item/select-item.scss
src/components/select/select-item/select-item.ts
src/components/select/select.html
src/components/select/select.lang.en.json
src/components/select/select.lang.fr.json
src/components/select/select.scss
src/components/select/select.stories.ts
src/components/select/select.ts
src/lang/en.ts
src/lang/fr.ts

Proposition d'un m-select pour le remplacement du m-dropdown.  Le m-select fonctionne avec les scoped slot offrant une plus grande flexibilité
Pour l'instant les fonctionnalités sont limité et le composante ne sera qu'utilisé dans le m-phonefield il faudrait voir si ca correspond a nos besoin dans l'éventuel remplacement du m-drowdown

Modul 1067  mselect pour remplacement éventuel du mdropdown

---

src/mixins/media-queries/media-queries.ts
src/styles/variables/_var-media-queries.scss
src/utils/media-queries/media-queries.ts

- Adding sounding names for media queries
- https://jira.dti.ulaval.ca/browse/MODUL-1090

MODUL-1090 - Adding sounding names to media queries

---

src/components/form/control-directive.ts
src/components/form/form.html
src/components/form/form.ts
src/utils/form/abstract-control.ts
src/utils/form/form-array.ts
src/utils/form/form-group.ts
src/utils/form/validators/control-validator.ts

pas de breaking change, juste du renommage et un peu de code format. 
@jsroy19  j'ai enlevé les commentaires dans ControlValidator, ils étaient misleading. On pourra en jaser!
pas de Jira

form clean up

---

package-lock.json
package.json

fix openshift storybook

---

src/utils/modul/modul.ts

Lorsqu'il y a un menu d'option ou liste déroulante en mobile dans une autre fenêtre comme overlay ou dialog, le module de gestion des stacks enlève les éléments de style sur le body et ne devrait pas.
[MODUL-1108](https://jira.dti.ulaval.ca/browse/MODUL-1108)

MODUL-1108 - Problème portal

---

src/components/datepicker/datepicker.ts
src/components/input-mask/input-mask.ts
src/components/timepicker/timepicker.ts

- [ x] Provide a small description of the changes introduced by this PR
fix problem with Cleave option typing

fix problem with Cleave typing

---

src/components/accordion/__snapshots__/accordion.stories.ts.snap
src/components/accordion/accordion.html
src/components/accordion/accordion.stories.ts
src/components/accordion/accordion.ts

Garder le contenu de l’accordéon dans le DOM
[MODUL-1115](https://jira.dti.ulaval.ca/browse/MODUL-1115)

MODUL-1115 - Garder le contenu de l’accordéon dans le DOM

---

src/components/phonefield/__snapshots__/phonefield.stories.ts.snap
src/components/phonefield/phonefield.scss
src/components/select/__snapshots__/select.stories.ts.snap
src/components/select/select.html

Des slots et des classes dans le m-input-style on été renommées en parallèle au développement de la composante ce qui à causé des régressions
[MODUL-1117](https://jira.dti.ulaval.ca/browse/MODUL-1117)

MODUL-1117 - Régression dans le phonefield

---

.github/CODEOWNERS

Ajout codeowner pour le modul address

Ajout code owner m-address

---

src/utils/i18n/i18n-service.sandbox.ts

fix a bug in sandboxe registration

fix i18n service sandboxe

---

src/components/form/fallouts/built-in-form-action-fallouts.ts
src/components/form/form.ts
src/sandboxes/form/form-complex.sandbox.html
src/sandboxes/form/form-complex.sandbox.ts
src/sandboxes/form/form-external-validation.sandbox.ts
src/utils/form/abstract-control.ts
src/utils/form/form-array.ts
src/utils/form/form-control.ts
src/utils/form/form-group.ts

Ajout d'abstraction pour ne pas avoir à faire du casting partout dans notre application. Exemple réel: ((seance as FormGroup).getControl('seanceUnique') as FormGroup).getControl('dateSeance').validate();
Il n'y a pas de breaking change.
https://jira.dti.ulaval.ca/browse/ENA2-6673

ENA2-6673 - Add abstraction to form and sandbox complex cases

---

src/filters/date/time/__snapshots__/time.stories.ts.snap
src/filters/date/time/time.lang.en.json
src/filters/date/time/time.lang.fr.json
src/filters/date/time/time.stories.ts
src/filters/date/time/time.ts

Fix hour offset on iphone
Time periods will display a '-' between their component unless a preposition is asked by the user
https://jira.dti.ulaval.ca/browse/MODUL-1116

different tweaks on the time filter

---

src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
src/components/datepicker/datepicker.html
src/components/datepicker/datepicker.stories.ts
src/components/form/__snapshots__/form.stories.ts.snap

https://jira.dti.ulaval.ca/browse/MODUL-1126
https://jira.dti.ulaval.ca/browse/ENA2-6810

MODUL-1126 - add required-marker prop for the datepicker component

---

src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
src/components/datepicker/datepicker.lang.en.json
src/components/datepicker/datepicker.lang.fr.json
src/components/form/__snapshots__/form.stories.ts.snap
src/components/timepicker/__snapshots__/timepicker.stories.ts.snap
src/components/timepicker/timepicker.lang.en.json
src/components/timepicker/timepicker.lang.fr.json

Accorder les messages avec le ton rédactionnel.
https://jira.dti.ulaval.ca/browse/MODUL-1135

MODUL-1135 Ajustements aux messages d'erreur du date et time picker

---

src/components/menu/menu-item/menu-item.html
src/components/menu/menu-item/menu-item.ts

fix major regression, menu-item used as subitem aren't visible.
https://jira.dti.ulaval.ca/browse/MODUL-1142
https://jira.dti.ulaval.ca/browse/ENA2-6960

MODUL-1142 - menu-item used as subitem aren't visible.

---

src/components/address/address-autocomplete-field/address-autocomplete-field.stories.ts
src/components/address/address-lookup-field/address-lookup-field.html
src/components/address/address-lookup-field/address-lookup-field.scss
src/components/address/address-lookup-field/address-lookup-field.ts

Seulement intégration du résultat de recherche, on à laissé tomber le lien de saisie manuelle pour le moment
[MODUL-1123](https://jira.dti.ulaval.ca/browse/MODUL-1123)

Modul-1123 Intégration champ recherche adresse

---

src/components/menu/menu-item/menu-item.ts
src/components/menu/menu.html
src/components/menu/menu.ts

Fix visuals regressions following changes in release 112
https://jira.dti.ulaval.ca/browse/MODUL-1144

MODUL-1144 - Fix menu visuals regressions

---

src/components/address/address-editor/__snapshots__/address-editor.stories.ts.snap
src/components/dropdown/__snapshots__/dropdown.spec.ts.snap
src/components/dropdown/__snapshots__/dropdown.stories.ts.snap
src/components/dropdown/dropdown.html
src/components/form/__snapshots__/form.stories.ts.snap

MODUL-1161 - change dropdown arrow size

---

src/components/transitions/accordion-transition/accordion-transition.ts

Change default value of prop disabled - m-accordion-transition
https://jira.dti.ulaval.ca/browse/MODUL-1149

BUG FIXE : Change default value of prop disabled - m-accordion-transition

---

src/components/menu/menu-item/menu-item.scss
src/components/menu/menu-item/menu-item.ts

When we click on selected menu-item, menu component close automatically.

MODUL-1171 - selected menu item css

---

src/components/address/address-editor/__snapshots__/address-editor.stories.ts.snap
src/components/copy-to-clipboard/__snapshots__/copy-to-clipboard.stories.ts.snap
src/components/copy-to-clipboard/copy-to-clipboard.html
src/components/copy-to-clipboard/copy-to-clipboard.stories.ts
src/components/copy-to-clipboard/copy-to-clipboard.ts
src/components/form/__snapshots__/form.stories.ts.snap
src/components/input-group/__snapshots__/input-group.stories.ts.snap
src/components/textfield/__snapshots__/textfield.stories.ts.snap
src/components/textfield/textfield.html
src/mixins/input-state/input-state.ts

Add input states to copy to clipboard component (waiting, readonly, disabled, etc)
https://jira.dti.ulaval.ca/browse/MODUL-1154
input-state: waiting state will now take precedence over readonly

Copy to clipboard input states

---

src/components/rich-text-editor/adapter/vue-froala.scss
src/styles/utils/_typography.scss
src/styles/variables/_var-font.scss

Garder le font-weight--black et modifier les balises strong du RTE sur un titre
[MODUL-1172](https://jira.dti.ulaval.ca/browse/MODUL-1172)

MODUL-1172 - Modifications font-weight du RTE

---

src/components/error-pages/error-access-denied/__snapshots__/error-access-denied.stories.ts.snap
src/components/error-pages/error-browser-not-supported/__snapshots__/error-browser-not-supported.stories.ts.snap
src/components/error-pages/error-config-not-supported/__snapshots__/error-config-not-supported.stories.ts.snap
src/components/error-pages/error-cookies-not-supported/__snapshots__/error-cookies-not-supported.stories.ts.snap
src/components/error-pages/error-page-not-found/__snapshots__/error-page-not-found.stories.ts.snap
src/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
src/components/message-page/__snapshots__/message-page.spec.ts.snap
src/components/message-page/message-page.html

MODUL-1162 - Fix breaking change introduce by m-link bullet-point props

---

src/components/rich-text-editor/adapter/vue-froala.scss

MODUL-1163 - RTE : fix vertical align labels in collapse mode

---

src/components/carousel/carousel.sandbox.html
src/components/carousel/carousel.ts

Added a swipeDisabled prop.
https://jira.dti.ulaval.ca/browse/MODUL-1175

MODUL-1175 - added swipeDisabled prop
