ulaval/modul-components

- conf/tslint/funcMethodReturnTypeRule.ts
- package-lock.json
- package.json
- src/utils/file/file.ts
- tests/app/router.ts
- tsconfig.dev.json
- tsconfig.json
Jeff, est-ce que tu peux valider que la modification que j'ai fait dans file.ts tient la route?
J'ai fixé le linter qui s'auto-lintait. Par contre, je me suis mis à avoir des problèmes avec une référence sur node_modules/tslint/lib/configuration.d.ts qui utilise des "Map" (es6). Avec un peu d'explorations, j'ai flushé le module @types/es6-promise pour utiliser ceux qui viennent avec Typescript (modifs dans tsconfig.json)... de là ma modification dans le retour de le promesse.
> Fix tslint;remove es6 promise & replace with es6 Typescript lib

- src/components/input-style/input-style.ts
- src/components/textarea-resize/textarea-resize.ts
- src/components/textarea/__snapshots__/textarea.spec.ts.snap
- src/components/textarea/textarea.html
- src/components/textarea/textarea.scss
- src/components/textarea/textarea.spec.ts
- src/components/textarea/textarea.ts
- src/directives/directive-names.ts
- src/directives/index.ts
- src/directives/textarea-auto-height/textarea-auto-height.spec.ts
- src/directives/textarea-auto-height/textarea-auto-height.ts
- src/mixins/input-management/input-management.ts
BREAKING CHANGES
- maxlength is now maxLength so attribute can be written as "max-length"
- textarea-resize is deprecated. Should use directive v-m-textarea-auto-height directly on a native textarea element
> Textarea - code review

- src/components/inplace-edit/inplace-edit.html
- src/components/inplace-edit/inplace-edit.spec.ts
- src/components/inplace-edit/inplace-edit.ts
Empêcher la propagation de l'événement lors du click sur les boutons enregistrer et supprimer pour éviter d'interragir avec les autres éléments pouvant écouter sur le click.
MODUL-63
BUGFIX - propagaiton du click sur les boutons enregistrer et annuler dans l'édition sur place
> MODUL-63 Prevenir propagation du click sur les boutons enregistrer et annuler

- src/components/radio-group/radio-group.scss
Removed display: inline-block on ul element of radio group to avoid unnecessary line break on Safari.
https://jira.dti.ulaval.ca/browse/MODUL-69
> Avoid unnecessary line break for inline radio group on Safari

- src/components/i18n/i18n.ts
- src/utils/i18n/i18n.spec.lang.fr.json
- src/utils/i18n/i18n.spec.ts
- src/utils/i18n/i18n.ts
- [ x] Provide a small description of the changes introduced by this PR
corrige l'erreur "Argument of type Object is not assignable to parameter of type 'any[] | undefined'"
- [ x] Include links to issues
https://jira.dti.ulaval.ca/browse/MODUL-88
> MODUL-88 - i18n - corrected type bug

- src/components/popper/popper.ts
When there is a lot of items or loading the items of the dropdown is long, the left positionning of the list isn't correct on the first opening.
It's okay on second opening and after that.
The first call to popper.js update() seem to append to early.
https://jira.dti.ulaval.ca/browse/MODUL-198
https://jira.dti.ulaval.ca/browse/AEL-206
> MODUL-198 Problème d'alignement du dropdown sur le chargement de plusieurs éléments

- src/components/character-count/__snapshots__/character-count.spec.ts.snap
- src/components/character-count/character-count.spec.ts
- src/components/character-count/character-count.ts
- src/components/textarea/textarea.html
- src/components/textarea/textarea.sandbox.html
- src/components/textarea/textarea.sandbox.ts
- src/components/textarea/textarea.ts
- src/components/textfield/textfield.html
- src/components/textfield/textfield.sandbox.html
- src/components/textfield/textfield.sandbox.ts
- src/components/textfield/textfield.ts
character-count will now display an error when max-length is not provided
text-area threshold prop renamed to character-count-threshold
text-field threshold prop renamed to character-count-threshold
https://jira.dti.ulaval.ca/browse/MODUL-75
- text-area threshold prop renamed to character-count-threshold
- text-field threshold prop renamed to character-count-threshold
> charactercount => display an error when maxlength is not provided

- src/utils/vue/directive.ts
The "sortable:add" event is not always fired when a draggable item is dropped into a dynamically added sortable list. The item which has the sortable:add event duplicate itself in the virtual DOM as a child of itself and the listeners are moved onto the child. So an additional check is made to emit the event from the child item to cover this strange case.
https://jira.dti.ulaval.ca/browse/MODUL-204
> MODUL-204 - quick fix emit "sortable:add" event

- src/directives/sortable/sortable.ts
CSS classes for displaying insertion markers are not added anymore on an invalid droppable element.
https://jira.dti.ulaval.ca/browse/MODUL-215
> MODUL-215 - drag and drop: marqueurs insertion

- src/directives/draggable/draggable-allow-scroll.ts
Fix regression for enum modification
@Mboulianne, j'ai fait les tests suivants, et ça fonctionne bien, ça devrait donc être correct si l'utilisateur de la directive utilise 'top' et 'bottom' en minuscules. Ça va suivre comme avec tous les enums des composantes qui fonctionnent également de cette façon.
Test que j'ai fait
```
enum Test {
Alpha = 'alpha',
Bravo = 'bravo'
}
...
protected mounted(): void {
let s: string = 'bravo';
this.testme(s as Test);
}
private testme(t: Test): void {
switch (t) {
case Test.Alpha:
console.log('switch alpha');
break;
case Test.Bravo:
console.log('switch bravo');
break;
default: console.log('??');
}
}
// output 'switch bravo'
```
https://jira.dti.ulaval.ca/browse/MODUL-241
> fix enum case sensitivity

- src/components/error-browser-not-supported/__snapshots__/error-browser-not-supported.spec.ts.snap
- src/components/error-browser-not-supported/error-browser-not-supported.html
- src/components/error-browser-not-supported/error-browser-not-supported.spec.ts
- src/components/error-browser-not-supported/error-browser-not-supported.ts
- src/components/error-page-not-found/error-page-not-found.ts
- src/components/error-template/__snapshots__/error-template.spec.ts.snap
- src/components/error-template/error-template.html
permettre de passer des props pour desktop et mobile dans browser non supporté
Régler deux problèmes dans les pages d'erreur, dans le Template, la gestion de l'ouverture du lien externe dans un nouvel onglet et interne dans le même onglet n'était pas complère (methode non appelée dans le template)
Aussi, permettre de passer des paramètres spécifique aux textes mobile et desktop dans le navigateur non supporté (avant permettait de switcher d'un texte à l'autre selon le mode d'affichage seulement si on prend le message d'erreur par défaut, il utilisait une seule valeur si on en passait un en props)
ENA2-2237
> ENA2-2237 - arranger bug : lien externe"interne mal géré + ajouter props pour messages desktop vs mobile

- src/components/progress/__snapshots__/progress.spec.ts.snap
- src/components/progress/progress.html
- src/components/progress/progress.sandbox.html
- src/components/progress/progress.spec.ts
- src/components/progress/progress.ts
Appliquer automatiquement l'état « complété » lorsque l'indicateur de progression atteint 100%
[MODUL-295](https://jira.dti.ulaval.ca/browse/MODUL-295)
> Appliquer automatiquement l'état « complété » lorsque l'indicateur de progression atteint 100%

- src/components/error-template/error-template.scss
Mettre le titre des pages d'erreurs sur deux lignes ( et plus ..)
https://jira.dti.ulaval.ca/browse/MODUL-348
> MODUL-348 - ajout d'une largeur maximal pour le titre page d'erreur

- src/components/error-config-not-supported/__snapshots__/error-config-not-supported.spec.ts.snap
- src/components/error-config-not-supported/error-config-not-supported.ts
Modifier la clé du message par défaut du hint de error-config-not-supported 
https://jira.dti.ulaval.ca/browse/MODUL-356
> MODUL-356 - modifier la clé du hint m-error-config-not-supported:hint.secondary

- src/components/input-style/input-style.scss
- src/components/rich-text-editor/adapter/vue-froala.scss
remove background-color from the editor when it is in read-only mode.
Fix word wrap and background-color for the rich-text
https://jira.dti.ulaval.ca/browse/MODUL-363
https://jira.dti.ulaval.ca/browse/MODUL-364
> fix word-wrap on the rte

- src/directives/droppable/droppable.spec.ts
- src/directives/droppable/droppable.ts
- src/directives/sortable/sortable.spec.ts
- src/directives/sortable/sortable.ts
Encapsulate a sortable so it won't accept items from another sortable
https://jira.dti.ulaval.ca/browse/MODUL-386
- Added a new modifier on sortable directive: encapsulate.  When active, it will render drag from another sortable impossible.
> Encapsulate a sortable so it won't accept items from another sortable

- src/components/dropdown/dropdown.sandbox.html
- src/components/dropdown/dropdown.sandbox.ts
- src/mixins/input-popup/input-popup.ts
Même comportement visuel, lorsque la valeur 'null' est attribuée au model du Dropdown que lorsque c'est la valeur 'undefined'
https://jira.dti.ulaval.ca/browse/MODUL-288
https://jira.dti.ulaval.ca/browse/AEL-209
> MODUL-288 - Same visual behaviour when model is set to null, as undef

- src/components/rich-text/rich-text.scss
First paragraph had a top margin in RTE reader.  It is not good since it can create some visual inconsistency.
https://jira.dti.ulaval.ca/browse/MODUL-409
> RTE in read mode => Remove the top margin of the first paragraph

- src/components/dropdown/dropdown.sandbox.html
- src/components/dropdown/dropdown.sandbox.ts
- src/mixins/input-popup/input-popup.ts
When internalValue is not a string, trim() can't be apply
https://jira.dti.ulaval.ca/browse/MODUL-440
https://jira.dti.ulaval.ca/browse/AEL-278
> It's impossible to select a dropdown option when it is a numeric value

- src/components/touch/touch.spec.ts
- src/components/touch/touch.ts
Tap event will not be emitted only once by the m-touch component.  This fix a bug where you could not toggle a property in the tap listener since it would instantly toggle and untoggle
https://jira.dti.ulaval.ca/browse/MODUL-455
> m-touch tap event are emitted twice which cause a bug in the carousel

- src/components/carousel/carousel.html
- src/components/carousel/carousel.sandbox.html
- src/components/carousel/carousel.sandbox.ts
- src/components/carousel/carousel.ts
- src/components/touch/enums.ts
- src/components/touch/touch.spec.ts
- src/components/touch/touch.ts
- src/components/touch/zingtouch.spec.ts
- src/components/touch/zingtouch.ts
Tap event was emitted twice on mobile devices and in device simulation on chrome.  Now it won't, but it could emited a tap and a click event at the same time (ghost click on mobile devices)
https://jira.dti.ulaval.ca/browse/MODUL-455
> Separate click and tap interaction when tapping on zingTouch

- src/components/datepicker/__snapshots__/datepicker.spec.ts.snap
- src/components/dialog/dialog.html
- src/components/dropdown/__snapshots__/dropdown.spec.ts.snap
- src/components/edit-window/edit-window.html
- src/components/edit-window/edit-window.ts
- src/components/modal/modal.html
- src/components/popper/popper.html
- src/components/popper/popper.ts
- src/components/sidebar/sidebar.html
- src/components/sidebar/sidebar.sandbox.html
- src/components/timepicker/__snapshots__/timepicker.spec.ts.snap
- src/mixins/portal/portal.ts
Si on utilisait souvent la Mixin portal, ça créait pas mal d'éléments superflus dans le DOM.  Maintenant, les éléments nécéssaires au bon fonctionnement d'un Portal seront mis en place au premier init de la mixin (première fois que propOpen = true).
Faire attention.  Il y a quelques breaking changes dans brio : 
-Un composant qui utilise la mixin Portal ne peut avoir un <portal> comme root element.
-Pour renseigner le target-el, il est maintenant conseillé d'utiliser la propriété portalTargetSelector dans la mixin.  L'id n'est plus disponible dès le départ, et un target-el qui contient '#' + propId (undefined) n'est pas valide aux yeux de vue-portal.  
-Si on utilise un portal contenant une transition, il est important d'attendre que l'élément portal soit bien monté dans le DOM afin que …
> Lazy load portal

- src/components/dialog/dialog.scss
- src/components/sidebar/sidebar.scss
En passant à un tap-highlight transparent, on évite que le dialog ou la sidebar devienne bleu en tappant dessus sur mobile.
https://jira.dti.ulaval.ca/browse/MODUL-490
https://jira.dti.ulaval.ca/browse/ENA2-62
> MODUL-490 - Changer le tap pour etre transparent

- src/components/rich-text-editor/adapter/vue-froala.ts
- src/components/rich-text-editor/rich-text-editor.sandbox.html
- src/components/rich-text-editor/rich-text-editor.sandbox.ts
Lors de la réutilisation d'un RTE pour la création de contenu, il est impossible de réinitialiser la valeur. Lorsque le champ récupère le focus, l'ancienne valeur du RTE est toujours présente.
Ce qui a été fait
* Possibilité de réinitialiser le contenu du RTE
* Ajout d'une démonstration dans le sandbox pour reproduire le bug / valider qu'il a été réglé
https://jira.dti.ulaval.ca/browse/MODUL-509
> MODUL-509 - Rafraichissement du RTE après le changement de la valeur du model

- src/components/login/__snapshots__/login.spec.ts.snap
- src/components/textfield/__snapshots__/textfield.spec.ts.snap
- src/components/textfield/textfield.html
- src/components/textfield/textfield.spec.ts
- src/components/textfield/textfield.ts
Fixed a weird case where we tried to set input style while the ref was not defined.  Moreover, reactivity should always be used instead of refs when possible.
https://jira.dti.ulaval.ca/browse/MODUL-492
- Possible breaking change dans les tests qui n'utilisent pas le shallowMount => Avant l'attribut "type" n'était pas render dans le dom.  Maintenant il l'est.
- MTextfieldType.EMail a été renommé en MTextfieldType.Email
> textfield Cannot read property 'setAttribute' of undefined

- src/assets/icons/sprites-default.svg
- add 2 icons :
- m-svg__arrow-return
- m-svg__arrow-head-circle--right
https://jira.dti.ulaval.ca/browse/MODUL-491
https://jira.dti.ulaval.ca/browse/ENA2-2024
> MODUL-491 - Ajouter les icônes manquantes pour ENA2-2024

- src/components/rich-text/rich-text.sandbox.html
- src/components/rich-text/rich-text.scss
RTE reader text doesn't wrap
https://jira.dti.ulaval.ca/browse/MODUL-504
> Fix incorrect word-break on rich-text in read mode

- src/components/rich-text-editor/__snapshots__/rich-text-editor.spec.ts.snap
- src/components/rich-text-editor/adapter/vue-froala.ts
- src/components/rich-text-editor/rich-text-editor.sandbox.html
- src/components/rich-text-editor/rich-text-editor.spec.ts
- src/components/rich-text-editor/rich-text-editor.ts
- src/mixins/input-management/input-management.ts
Added a method in input-management to allow a component to override the behavior of the method `hasValue`. This change was needed to allow the RTE to be considered empty in those cases:
- RTE contains only empty HTML tags (`<div><p><p></div>`)
- RTE contains only HTML tags and spaces (`<div>&nbsp; &nbsp;</div>`)
- RTE contains only HTML tags, spaces and returns (`<div>&nbsp; \n \n</div>`)
https://jira.dti.ulaval.ca/browse/MODUL-482
> Added a check for RTE containing only HTML

- src/components/dropdown/__snapshots__/dropdown.spec.ts.snap
- src/components/dropdown/dropdown.lang.fr.json
- src/components/dropdown/dropdown.spec.ts
- src/components/dropdown/dropdown.ts
Re-added the "hasFooterSlot" computed property in dropdown.ts since it was removed while still being referenced in the component html. 
It seems to have been removed last October with the following merge commit:
https://github.com/ulaval/modul-components/commit/260a3cabc332cf8c4fa428cb528622c7254938a7#diff-32d19fa68636b089eb226685394c1f32
This caused a few errors to be displayed in the console each time a dropdown was rendered. I'm unsure if this is the best way to fix the problem or if its removal was preferred.
https://jira.dti.ulaval.ca/browse/MODUL-464
> MODUL-464 : Fix for dropdown undefined property HasFooterSlot

- src/components/template/template.html
- src/components/template/template.sandbox.html
- src/components/template/template.sandbox.ts
- src/components/template/template.scss
- src/components/template/template.ts
Lorsque le composant m-template est utilisé, il est impossible d'utiliser un v-if sur les slots.
Pour régler le problème, utiliser le $slots directement dans le template.
Ajouter la prop paddingBody: boolean
https://jira.dti.ulaval.ca/browse/MODUL-514
https://jira.dti.ulaval.ca/browse/AEL-294
> MODUL-514 - Rendre asynchrone les slots du composant m-template

- src/components/modal/modal.scss
Transparent tap on modal instead of a blue tap.
https://jira.dti.ulaval.ca/browse/MODUL-490
This modification had already been merged in https://github.com/ulaval/modul-components/pull/498
but it seems it had been partially removed during the renaming of dialog and modal.
> MODUL-490 - Transparent tap on modal

- src/components/navbar-item/navbar-item.scss
- src/components/navbar/navbar.sandbox.html
Il manque une bordure dans le navbar (skin:tab-light) lorsqu'il y a seulement un item.
Voir l'image du billet (https://jira.dti.ulaval.ca/browse/MODUL-539)
https://jira.dti.ulaval.ca/browse/MODUL-539
https://jira.dti.ulaval.ca/browse/AEL-303
> MODUL-539: Il manque une bordure dans le navbar (skin:tab-light) lorsqu'il y a seulement un item

- src/assets/icons/sprites-default.svg
- src/components/datepicker/datepicker.html
- src/components/input-style/input-style.html
- tests/app/app-frame/app-frame.html
- tests/app/app-frame/app-frame.scss
- tests/app/attributes/attributes.html
- tests/app/index.html
- tests/app/media-queries/media-queries.html
- tests/app/navigation/navigation.html
- tests/app/viewer/viewer.html
Ajouter l'icône not-allowed au textfield et l'icône chevron--right au datepicker (voir les photos dans le billet MODUL-545)
J'ai **mis à jour** le visuel des template de la section sandbox.
- Suppression des m-flex-template qui servait à rien
- Nouveau style et balisage pour le composant m-app-frame
https://jira.dti.ulaval.ca/browse/MODUL-545
> MODUL-545: Ajouter l'icône not-allowed au textfield et l'icône chevron--right au datepicker	

- src/components/navbar-item/navbar-item-helper.ts
- src/components/navbar-item/navbar-item.html
- src/components/navbar-item/navbar-item.spec.ts
- src/components/navbar-item/navbar-item.ts
- src/components/navbar/navbar.ts
1- Je sais pas pourquoi on y a été avec une propriété "selected" dans le navbar au lieu d'utiliser le truc built-in de vue-router 
https://router.vuejs.org/api/#linkactiveclass
2- Considérant qu'on a pas utilisé le comportement de built-in de vue, c'est vraiment chiant d'avoir à gérer le tab actif quand on travail avec le router.  Sans vouloir tout remanier, je propose la modif suivante qui, sur le mounted, va aller chercher si le linkactiveclass est contenue dans un navbar-item.. si c'est le cas j'initialise le selected avec cette valeur.
3- J'avais peur de créer des régressions, j'ai donc mis un guard sous la forme d'une prop que j'ai appellé autoselect.
https://jira.dti.ulaval.ca/browse/MODUL-546
> Autoselect router-active tab when it exists on mounted

- src/components/steppers-item/steppers-item.html
- src/components/steppers-item/steppers-item.scss
- src/components/steppers-item/steppers-item.ts
- src/components/steppers/steppers.html
- src/components/steppers/steppers.sandbox.html
- src/components/steppers/steppers.scss
- src/components/steppers/steppers.ts
1) En mode "shell", dans l'admission, le train disparaît lorsqu'on accède à la section directement par l'URL
Voir les photos du billet (https://jira.dti.ulaval.ca/browse/MODUL-538)
2) Rendre disponible la navigation à l'aide du `<router-link>` dans le `<m-steppers-item>`
https://jira.dti.ulaval.ca/browse/MODUL-538
Ajout de la nouvelle prop `url` sur le composant `<m-steppers-item>`. Grâce a cette prop, il est maintenant possible de naviguer à l'intérieur d'un `<m-steppers>` à l'aide d'un `<router-link>`.
> MODUL-538: Dans l'admission, le train disparaît lorsqu'on accède à la section directement par l'URL

- src/components/dropdown/__snapshots__/dropdown.spec.ts.snap
- src/components/dropdown/dropdown.html
- src/components/option/__snapshots__/option.spec.ts.snap
- src/components/option/option.ts
- src/components/sidebar/sidebar.scss
- src/components/tooltip/tooltip.html
- src/utils/modul/modul.ts
1) Lorsqu'on affiche une fenêtre (m-dialog, m-modal, m-sidebar, etc.), on ne devrait par remonter en haut de la page
Pour reproduire le problème, cliquez sur un bouton qui ouvrira n'importe quel type de fenêtre (m-dialog, m-modal, m-sidebar, etc.). Ce bouton devrait être positionné dans le bas d'une page possédant un scroll. Vous constaterez qu'à l'ouverture de la fenêtre, le scroll de la page remonte en haut de la page.
Le comportement souhaité est de conserver la position du scroll actuelle à l'ouverture d'une fenêtre tout en stoppant le scroll.
2) Ajustement de la prop **focus-management** pour composant utilisant `<m-popper>`
https://jira.dti.ulaval.ca/browse/MODUL-554
https://jira.dti.ulaval.ca/browse/AEL-345
> MODUL-554 - Ajustement du comportement et de l'accessibilité des fenêtres (m-modal, m-dialog, m-popup, m-dropdown, etc.) 

- src/mixins/portal/portal.ts
Watch is now immediate, so when the component is instancialized, it checks immediatly the value of the 'open' prop instead of waiting for a change.
https://jira.dti.ulaval.ca/browse/MODUL-576
https://jira.dti.ulaval.ca/browse/ENA2-3591
The watch of the prop 'Open' on portal components (dialog, modal, popper, sidebar) is now immediate.
BREAKING CHANGE: If your variable that was binded to the prop Open was at true during instancialization of the portal component, it will now show the component instead of now showing the component.
Minimalist example that will now work: `<m-dialog :open="true">Text<m-dialog>`
> Add immediate watch on portal components

- src/components/link/link.html
- src/components/link/link.sandbox.html
- src/components/link/link.sandbox.ts
- src/components/link/link.spec.ts
- src/components/link/link.ts
Un MLink en mode RouterLink ET disabled ne navigue plus vers sa destination lorsque cliqué.
https://jira.dti.ulaval.ca/browse/MODUL-561
> MODUL-561 Lien mode RouterLink et disabled ne doit plus naviguer lorsque cliquer

- src/utils/modul/modul.ts
Il s'agit d'un P1 dans Brio!
Lorsqu'on scroll dans la page, qu'on ouvre un m-overlay et qu'on ouvre le menu d'options, il n'apparaît pas à la bonne place. Il se positionne en fonction du scroll qu'on a effectué dans la page. Voir le billet modul pour une vidéo du problème. @raphpare a trouvé la solution!
https://jira.dti.ulaval.ca/browse/MODUL-593
https://jira.dti.ulaval.ca/browse/ENA2-3652
> P1 - Problème lors dans le positionnement du m-option

- src/utils/i18n/i18n.spec.lang.fr.json
- src/utils/i18n/i18n.spec.ts
- src/utils/i18n/i18n.ts
CANCEL AND REPLACE PR : https://github.com/ulaval/modul-components/pull/528
Cas d'utilisation ayant mené à cette amélioration:
Possibilité de formatter une chaine de caractère avec des espaces insécable et rendre ce formattage plus explicite dans les fichiers de traduction.
Actuellement dans les fichiers de traduction, un espace insécable est représenté comme:
%(date)s à %(time)s
La proposition de changement:
%(date)s à%(\_NBSP\_)s%(time)s
https://jira.dti.ulaval.ca/browse/MODUL-523
Added special characters support for translation string. These special characters can only be used with `FormatMode.Sprintf` and `FormatMode.Vsprintf`.
```
| Character           | unicode symbol | HTML symbol | usage in translation file 
| Non-breaking space  | `\u00a0`       | `&nbsp;`    | %(_NBSP_)s …
```
> Added special chars for translations

- src/components/input-style/input-style.scss
- src/components/textfield/textfield.sandbox.html
Ajustement du visuel du m-input-style lorsque la prop `:valid="true"`.
https://jira.dti.ulaval.ca/browse/MODUL-643
https://jira.dti.ulaval.ca/browse/GIN-321
> MODUL-643 - Un champ de saisie avec la prop valid="true" devrait être vert

- src/styles/base/_base.scss
fix @font-face not working inside @support rule in edge
https://jira.dti.ulaval.ca/browse/MODUL-647
http://feature-modul-647-font-face-ul-modul-dv01.pca.svc.ulaval.ca/typo-and-styles
> MODUL-647 - fix @font-face not working inside @support rule in edge

- src/components/tree/tree-node/tree-node.spec.ts
- src/components/tree/tree-node/tree-node.ts
I noticed a small bug I propably added while refactoring code during my last pull request. 
ParentAutoSelectMode will now react to children going from selected to unselected by switching to indeterminated or off. 
https://jira.dti.ulaval.ca/browse/MODUL-582
> MODUL-582 - Fixed parent auto-select multinode, added a test

- src/utils/svg/sprites.ts
SpritesService's addSprite methode returns the div id, so it can be used in m-icon
- [x ] Include links to issues
https://github.com/ulaval/modul-components/issues/654
> addSprites returns the div ID, so it can be used with any sprite

- src/components/table/table.sandbox.html
- src/components/table/table.sandbox.ts
- src/components/table/table.scss
Deleted word-break: break-word css propety since it is not supported on Firefox.
Added table-layout: fixed and width: 100% on table element and word-wrap: break-word on th/td elements.
Breaking change : Table now spans across all available space. Columns without explicit width will distribute remaining space evenly.
https://jira.dti.ulaval.ca/browse/MODUL-665
> MODUL-665 - M-Table - word-break: break-word

- src/components/form/__snapshots__/form.spec.ts.snap
- src/components/form/form.html
- src/components/form/form.scss
- src/components/form/form.spec.ts
- src/components/form/form.ts
Utilisation de style scopé pour le formulaire
https://jira.dti.ulaval.ca/browse/MODUL-716
> MODUL 716 - style scopé pour formulaire

- src/components/rich-text-editor/adapter/vue-froala.ts
RTE now closes after mouseup event occured. This prevents bugs when clicking controls below an open RTE.
https://jira.dti.ulaval.ca/browse/MODUL-704
> MODUL-704 - improve RTE blur management

- src/components/form/form-field.ts
J'avais modifié un algo selon une suggestion en code revue et je n'avais pas retesté tout le flow. Apparament le champs disparaissait si il devait focusser après cette modif.
https://jira.dti.ulaval.ca/browse/MODUL-729- 
[ ] Openshift deployment requested
> MODUL-729 - formfield disparait si doit être focus

- src/components/rich-text-editor/rich-text-editor.ts
With @Emit decorators, event names must be used as is in html templates. We prefer using kebab case in html files and we enforce it in other projects depending on modul, so now event names in @Emit are kebab case.
https://jira.dti.ulaval.ca/browse/MODUL-752
> MODUL-752 - m-rich-text-editor kebab case for event names

- src/components/datepicker/datepicker.html
- src/components/datepicker/datepicker.ts
- src/components/daterangepicker/daterangepicker.html
- src/components/periodpicker/periodpicker.sandbox.html
- src/components/periodpicker/periodpicker.sandbox.ts
- src/components/periodpicker/periodpicker.spec.ts
- src/components/periodpicker/periodpicker.ts
- src/utils/modul-date/modul-date.spec.ts
- src/utils/modul-date/modul-date.ts
period picker wasn't working with ISO date string
values returned by the "dateTo" model will now be set at end of the day by default
https://jira.dti.ulaval.ca/browse/MODUL-780
> Make periodpicker works with iso dates

- src/components/rich-text-editor/adapter/vue-froala.scss
- src/styles/mixins/_froala.scss
Moved images styles from vue-froala to mixin m-commons-froala-styles used by both m-rich-text-editor and m-rich-text.
https://jira.dti.ulaval.ca/browse/MODUL-791
> MODUL-791 - moved images styles into common mixin

- src/components/radio-group/__snapshots__/radio-group.spec.ts.snap
- src/components/radio-group/radio-group.html
- src/components/radio-group/radio-group.sandbox.html
- src/components/radio-group/radio-group.scss
…dio-goup
Ajuster l'espacement du message de validation du m-radio-group
https://jira.dti.ulaval.ca/browse/MODUL-798 
https://jira.dti.ulaval.ca/browse/MODUL-798
Revoir l'alignement du composant m-radio-group, car il ne possède plus de margin-top par défaut.
> MODUL-798 - Ajuster l'espacement du message de validation du m-radio-group

- src/styles/mixins/_froala.scss
When cursor is positionned next to a centered image, cursor no longer takes full height of image. 
https://jira.dti.ulaval.ca/browse/MODUL-819
> MODUL-819 - m-rich-text-editor : cursor behaviour fix

- src/components/form/form.ts
Problème survenue avec GIN et les toast behavior: Si on a un form validator (en plus des field validator) le toast dit de verifier les X champs alors que le form a X-1 champs. 
https://jira.dti.ulaval.ca/browse/MODUL-825
> MODUL-825 - Seulement considérer les erreurs des champs dans le message du toast du formulaire

- src/components/periodpicker/periodpicker.spec.ts
- src/components/periodpicker/periodpicker.ts
period picker model is now updated only when blur / selection end occurs.  This allows easier validation (No validation breaking when picking from date when we have not had the chance to pick a date to yet)
https://jira.dti.ulaval.ca/browse/MODUL-823
> periodpicker: Update model on blur only

- src/components/tooltip/tooltip.scss
Changement d'épaisseur et de position du underline sur le tooltip__link
https://jira.dti.ulaval.ca/browse/MODUL-814
> MODUL-814 - Changed underline on tooltip__link

- src/components/datepicker/__snapshots__/datepicker.spec.ts.snap
- src/components/error-message/__snapshots__/error-message.spec.ts.snap
- src/components/menu/menu-item/menu-item.html
- src/components/message/__snapshots__/message.spec.ts.snap
- src/components/message/message.html
- src/components/message/message.scss
- src/components/page-not-found/__snapshots__/page-not-found.spec.ts.snap
- src/components/session-expired/__snapshots__/session-expired.spec.ts.snap
- src/components/timepicker/__snapshots__/timepicker.spec.ts.snap
- src/components/toast/toast.html
- src/components/validation-message/__snapshots__/validation-message.spec.ts.snap
- src/components/validation-message/validation-message.html
Suite aux modifications de ce billet MODUL-812, certaine icones s'affichent avec la mauvaise taille.
Pour tester les modification aller voir les sandbox des composants suivant:
- m-message
- m-validation-message
- m-toast
https://jira.dti.ulaval.ca/browse/MODUL-851
> MODUL-851: Ajuster la largeur des icones dans les composants modul

- src/components/form/form-field.spec.ts
- src/components/form/form-field.ts
- src/utils/form/form-field/form-field.ts
C'est finalement utile dans certain cas. Comme par exemple les validation de cohérence entre les champs. On peut vouloir valider un champs seulement lorsqu'un autre est touché.
https://jira.dti.ulaval.ca/browse/MODUL-857
> MODUL-857 - Remettre la propriété touched au formulaire 

- README.md
- package.json
storybook will now replace snadboxes when running with npm run dev. Readme was updated
> Storybook to replace sandbox when running npm run dev

- src/components/dialog/dialog.scss
Add min-width: 100%; on the m-dialog_hint-body CSS Class so in order to correct a visual problem when the text contained in the element m-dialog_hint-text is not long enough.
https://jira.dti.ulaval.ca/browse/MODUL-898
> MODUL-898 - Add min-width: 100% on m-dialog_hint–body

- src/components/rich-text-editor/rich-text-editor-options.ts
- src/components/rich-text-editor/rich-text-editor.sandbox.html
- src/components/rich-text-editor/rich-text-editor.sandbox.ts
- src/components/rich-text-editor/rich-text-editor.spec.ts
- src/components/rich-text-editor/rich-text-editor.ts
We can now specify options by passing an array of MRichTextEditorOption to the options prop instead of a MRichTextEditorMode to the mode prop. MRichTextEditorMode can still be used but is now deprecated and will be removed soon.
https://jira.dti.ulaval.ca/browse/MODUL-881
> MODUL-881 - RTE modular options

- src/components/textfield/textfield.ts
on textfield reinitialization
Fix error occuring when reinitializing textfield value to undefined
https://jira.dti.ulaval.ca/browse/MODUL-901
> fix can't access length of undefined error on textfield

- src/components/textfield/textfield.html
- src/mixins/input-management/input-management.ts
…nagement
Retirer les validateurs de la prop autocomplete du input-management, car l'attribut HTML autocomplete accepte beaucoup plus de valeurs que celles du validateur actuel.
Exemple de valeurs acceptées dans l'autocomplete: https://developers.google.com/web/fundamentals/design-and-ux/input/forms/#recommended_input_name_and_autocomplete_attribute_values
-[x] Include links to issues
https://jira.dti.ulaval.ca/browse/MODUL-904
L'enum InputManagementAutocomplete a été supprimé.
> MODUL-904:  Retirer les validateurs de la prop autocomplete du input-management

- src/components/form/form.plugin.ts
- src/utils/toast/toast-service.plugin.ts
- src/utils/toast/toast-service.sandbox.ts
- src/utils/toast/toast-service.spec.ts
- src/utils/toast/toast-service.ts
Pour permettre plus de flexibilité aux projets utilisant modUL, la déclaration du plugin de service de toast a été séparée du service de toast
The file required to register the toast plugin has changed. Instead of importing `@ulaval/modul-components/dist/utils/toast/toast-service` the file `@ulaval/modul-components/dist/utils/toast/toast-service.plugin` must be imported instead
The name of the plugin remains unchanged  `ToastServicePlugin`.
https://jira.dti.ulaval.ca/browse/MODUL-916
> MODUL-916 - Separated toast service plugin from toast service:

- src/components/rich-text-editor/adapter/vue-froala.ts
- src/components/rich-text-editor/rich-text-editor.sandbox.html
Pasting image into RTE is no longer possible. This is to enforce use of m-file-upload for adding images.
https://jira.dti.ulaval.ca/browse/MODUL-925
> MODUL-925 - Prevent adding images into RTE without using m-file-upload

- src/components/toast/toast.spec.ts
- src/components/toast/toast.ts
> MODUL-934 - Add recount for timeout in toaster when mouse leave

- src/components/table/__snapshots__/table.spec.ts.snap
- src/components/table/__snapshots__/table.stories.ts.snap
- src/components/table/table.html
- src/components/table/table.scss
- src/components/table/table.ts
Les flèches dans l'entête, qui servent à trier le contenu du tableau, se positionnent à la mauvaise place lorsqu'un titre est long.
Voir la capture d'écran du billet [MODUL-975](https://jira.dti.ulaval.ca/browse/MODUL-975)
- Ajout de la propriété `class` à MCloumnTable permettant d'ajouter une classe sur la balise `<th>`
https://jira.dti.ulaval.ca/browse/MODUL-975
Le visuel de la flèche de trie de l'entête de tableau a été modifié.
> MODUL-975: Ajuster le visuel de l'entête des tableaux en mode sortable

- src/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
- src/components/accordion-group/accordion-group.html
- src/components/accordion-group/accordion-group.scss
- src/components/accordion-group/accordion-group.stories.ts
- src/components/accordion-group/accordion-group.ts
Amélioration de l'entête du m-accordion-group
[MODUL-980](https://jira.dti.ulaval.ca/browse/MODUL-980)
La prop **reverseHeader** change pour **toggleLinkLeft** pour être plus symbolique. Le comportement n'a pas changé, seulement à renommer la prop pour le nouveau nom
> MODUL-980 - Amélioration de l'entête du m-accordion-group

- src/components/dropdown/dropdown.scss
- src/components/icon/__snapshots__/icon.stories.ts.snap
- src/components/input-style/__snapshots__/input-style.stories.ts.snap
- src/components/input-style/input-style.scss
- src/components/input-style/input-style.stories.ts
Dans le input-style, le display-flex permettait d'aligner verticalement l'icône dans un dropdown mais créait un problème dans le RTE (voir billet). Comme le input-style est utilisé dans le RTE et que le RTE est "fragile", j'ai préféré ajouter un cas dans le storybook du input-style.
https://jira.dti.ulaval.ca/browse/MODUL-996
> MODUL-996 - Correction affichage RTE

- package.json
- src/components/form/__snapshots__/form.stories.ts.snap
- src/components/form/control-directive.ts
- src/components/form/fallouts/built-in-form-action-fallouts.ts
- src/components/form/form.html
- src/components/form/form.sandbox.html
- src/components/form/form.sandbox.ts
- src/components/form/form.stories.ts
- src/components/form/form.ts
- src/components/message/message.ts
- src/utils/form/abstract-control.ts
- src/utils/form/form-array.ts
- src/utils/form/form-contols.spec.ts
- src/utils/form/form-control.ts
- src/utils/form/form-group.ts
- src/utils/form/validators/between/between.ts
- src/utils/form/validators/compare/compare.ts
- src/utils/form/validators/control-validator.ts
- src/utils/form/validators/email/email.ts
- src/utils/form/validators/max-length/max-length.ts
- src/utils/form/validators/max/max.ts
- src/utils/form/validators/min-length/min-length.ts
- src/utils/form/validators/min/min.ts
- src/utils/form/validators/required/required.ts
- Changement de la fonction de validation pour séparer la validation async de la validation sync. De cette facon les validation sync retourne directement ce qui evite d'avoir un delai entre la validation et la mise a jour des erreurs dans le visuel (dans le cas des validation sync)
- Les validateurs async doivent mainteannt mettre le flag async a true et retourner une Promise<boolean>
- Modification des sandboxes pour la validation async et external
> MODUL-1002 - fix async and external validation

- src/components/accordion/accordion.scss
* Supprimer le padding-bottom du corps du m-accordion avec le skin="light"
* Aligner le contenu du corps de l'accordéon avec le titre (contenu de l'entête) de l'accordéon
https://jira.dti.ulaval.ca/browse/MODUL-1019
The padding-bottom of m-accordion body is remove when skin="light".
> MODUL-1019 : Supprimer le padding-bottom du m-accordion avec le skin="light"

- src/components/dropdown/__snapshots__/dropdown.stories.ts.snap
- src/components/dropdown/dropdown.html
- src/components/dropdown/dropdown.scss
- src/components/dropdown/dropdown.ts
Impossible de mettre un padding sur le pseudo élément ::placeholder, onn doit donc cacher l'icône sur ses navigateurs
[MODUL-1013](https://jira.dti.ulaval.ca/browse/MODUL-1013)
> MODUL-1013 - Enlever le placeholder icon sur Firefox et Edge

- src/components/decimalfield/__snapshots__/decimalfield.stories.ts.snap
- src/components/decimalfield/decimalfield.html
- src/components/decimalfield/decimalfield.ts
- src/components/input-mask/input-mask.html
- src/components/input-mask/input-mask.ts
- src/components/integerfield/__snapshots__/integerfield.spec.ts.snap
- src/components/integerfield/integerfield.html
- src/components/integerfield/integerfield.sandbox.html
- src/components/integerfield/integerfield.ts
- src/components/moneyfield/__snapshots__/moneyfield.spec.ts.snap
Integerfield now use cleavejs
Integerfield and decimalfield use inputmode decimal
Integerfield you can now type in 0 as first caracter
. and , will work to input the decimal-mark
https://jira.dti.ulaval.ca/browse/MODUL-1014
max-length on integerfield now has to be a number (max-length="1" becomes :max-length="1")
> Integerfield now use cleavejs

- src/assets/icons/sprites-default.svg
Ajouter 2 icône pour retirer avec un cercle remplie ou vide
[MODUL-1047](https://jira.dti.ulaval.ca/browse/MODUL-1047)
> MODUL-1047 - Ajout des icônes m-svg__remove-circle et m-svg__remove-circle-filled

- src/components/table/__snapshots__/table.spec.ts.snap
- src/components/table/__snapshots__/table.stories.ts.snap
- src/components/table/table.html
- src/components/table/table.scss
- src/components/table/table.stories.ts
- src/components/table/table.ts
* Ajout de la valeur `simple` à la prop skin.
* Ajout de la prop `rowHighlightedOnHover: boolean = true` qui permet de retirer l'effet de survol bleu sur les lignes du tableau.
https://jira.dti.ulaval.ca/browse/MODUL-1075
> MODUL-1075: Ajouter des styles sur le composant m-table

- src/components/expandable-layout/expandable-layout.ts
Renamed mode prop to panelScrollMode and MExpandableLayoutMode enum to MExpandableLayoutPanelScrollMode.
https://jira.dti.ulaval.ca/browse/MODUL-1084
> MODUL-1084 - m-expendable-layout : renamed mode prop

- src/styles/variables/_var-font.scss
Avec l'arrivée des titres dans le RTE, on va avoir beaucoup d'occurences de h4-5-6. Il devient donc important de différencier chaque niveau, même en mobile (actuellement H4-5-6 sont identique à 16px et une graisse de 500).
https://jira.dti.ulaval.ca/browse/MODUL-1086
En mobile, la grosseur des titres a été modifié.
> MODUL-1086 - Changer font-size des titres en mobile

- src/components/character-count/__snapshots__/character-count.spec.ts.snap
- src/components/character-count/character-count.html
- src/components/character-count/character-count.ts
- src/components/form/__snapshots__/form.stories.ts.snap
- src/components/textarea/textarea.html
- src/components/textarea/textarea.ts
- src/components/textfield/__snapshots__/textfield.stories.ts.snap
- src/components/textfield/textfield.html
- src/components/textfield/textfield.stories.ts
- src/components/textfield/textfield.ts
…tenu à l'intérieur du <m-textfield>
* Ajouter l'attribut HTML max-length sur le <textarea> contenu à l'intérieur du `m-textfield`
* Améliorer l'animation d'apparition (accordion-transition) du composant `m-character-count`
* Supprimer le getter `hasCounterTransition()` du `m-textfield` et du `m-textarea`. L'animation du `m-character-count` doit toujours être active même lorsque le champ est en erreur.
https://jira.dti.ulaval.ca/browse/MODUL-1080
> MODUL-1080 : Ajouter l'attribut HTML max-length sur le <textarea> contenu à l'intérieur du <m-textfield>

- src/components/datepicker/datepicker.html
- src/components/datepicker/datepicker.scss
Ajouter le label du datepicker dans l'entête de la fenêtre en version mobile (voir l'image du billet [MODUL-1088](https://jira.dti.ulaval.ca/browse/MODUL-1088))
**Raison de l'ajout de l'entête**
Dans le sélecteur de période en version mobile lorsque la fenêtre est ouverte, il est difficile de savoir si nous sélectionnons la date de début ou la date de fin.
https://jira.dti.ulaval.ca/browse/MODUL-1088
> MODUL-1088: Ajouter un entête à la fenêtre du datepicker en version mobile

- src/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
- src/components/add/__snapshots__/add.stories.ts.snap
- src/components/error-message/__snapshots__/error-message.spec.ts.snap
- src/components/error-pages/error-access-denied/__snapshots__/error-access-denied.stories.ts.snap
- src/components/error-pages/error-browser-not-supported/__snapshots__/error-browser-not-supported.stories.ts.snap
- src/components/error-pages/error-config-not-supported/__snapshots__/error-config-not-supported.stories.ts.snap
- src/components/error-pages/error-cookies-not-supported/__snapshots__/error-cookies-not-supported.stories.ts.snap
- src/components/error-pages/error-page-not-found/__snapshots__/error-page-not-found.stories.ts.snap
- src/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
- src/components/link/__snapshots__/link.stories.ts.snap
- src/components/link/link.html
- src/components/link/link.scss
- src/components/page-not-found/__snapshots__/page-not-found.spec.ts.snap
- src/components/pagination/__snapshots__/pagination.stories.ts.snap
- src/components/repeater/__snapshots__/repeater.stories.ts.snap
- src/components/session-expired/__snapshots__/session-expired.spec.ts.snap
Supprimer la marge à doite du m-add lorsqu'il n'y a aucun contenu (voir image du billet [MODUL-1091](https://jira.dti.ulaval.ca/browse/MODUL-1091)).
https://jira.dti.ulaval.ca/browse/MODUL-1091
**m-add and m-link:** Delete margin-right of icon when the slots.default is undefined
> MODUL-1091: Supprimer la marge à droite du m-add lorsqu'il n'y a aucun contenu

- src/components/table/table.scss
Voir la capture du billet [MODUL-1096](https://jira.dti.ulaval.ca/browse/MODUL-1096.), normalement, la barre de chargement devrait être collée entre l'entête et le corps du tableau.
https://jira.dti.ulaval.ca/browse/MODUL-1096.
> MODUL-1096: m-table : Supprimer le padding autour de la barre de chargement

- src/components/periodpicker/periodpicker.ts
fix error when passing undefined value to the periodpicker
https://jira.dti.ulaval.ca/browse/MODUL-1102
> fix error when passing undefined value to the periodpicker

- src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
- src/components/datepicker/datepicker.html
- src/components/datepicker/datepicker.scss
- src/components/datepicker/datepicker.spec.ts
- src/components/datepicker/datepicker.ts
- src/components/form/__snapshots__/form.stories.ts.snap
- src/components/periodpicker/__snapshots__/periodpicker.stories.ts.snap
Remove extra margin at the bottom of the date picker when no message is present
The datepicker will now behave like all other modUL fields
https://jira.dti.ulaval.ca/browse/MODUL-1099
> Remove extra margin at the bottom of the date picker when no message is present

- src/components/dropdown/dropdown.scss
- src/components/textarea/textarea.scss
- src/components/timepicker/timepicker.scss
* Ajouter un margin-right automatique sur le dropdown comme sur les autres inputs
* Ajouter la mixin CSS **m-input-inline-spacing();** sur le m-dropdown et le m-textarea
Voir image du billet [MODUL-1100](https://jira.dti.ulaval.ca/browse/MODUL-1100)
https://jira.dti.ulaval.ca/browse/MODUL-1100
> MODUL-1100 - Ajouter un margin-right automatique sur le dropdown et le textarea

- src/components/dropdown/dropdown.html
- src/components/dropdown/dropdown.ts
- src/components/file-upload/file-upload.html
- src/components/file-upload/file-upload.ts
- src/components/popper/popper.ts
- src/components/popup/popup.html
- src/components/popup/popup.ts
- src/mixins/portal/portal.ts
Uniformation de la nomenclature des emits des mixins portal.ts
Ces modifications impacteront tout les composant utilisant la mixin portal.ts
https://jira.dti.ulaval.ca/browse/MODUL-1092
New $emit adds after the closing delay : **portal-after-close**
Emits standardization for mixins portal.ts
| Old emit | New emit |
| ------------- | ------------- |
| beforeClose | portal-before-close  |
| portal-content-visible  | portal-after-open |
| portal-content-mounted  | portal-mounted |
| - | portal-after-close |
> MODUL-1092 - Ajouter un événement à la fin de l'animation de fermeture des fenêtres (mixin portal)

- src/components/searchfield/__snapshots__/searchfield.stories.ts.snap
- src/components/searchfield/searchfield.scss
- src/components/searchfield/searchfield.stories.ts
Increase css specificity to overrider input-style placeholder color
https://jira.dti.ulaval.ca/browse/MODUL-1114
> MODUL-1114 - the searchfield placeholder color is too light

- src/components/copy-to-clipboard/__snapshots__/copy-to-clipboard.stories.ts.snap
- src/components/copy-to-clipboard/copy-to-clipboard.html
- src/components/copy-to-clipboard/copy-to-clipboard.stories.ts
- src/components/copy-to-clipboard/copy-to-clipboard.ts
Make copy-to-clipboard use all it's container width by default
https://jira.dti.ulaval.ca/browse/MODUL-1125
> Make copy-to-clipboard use all it's container width by default

- src/components/form/form.lang.fr.json
Rétablir la formulation initiale « à revoir » plutôt que « à corriger ».
https://jira.dti.ulaval.ca/browse/MODUL-1127
Error message in m-form toast displayed when more than one error happens at submit has slighly changed.
> MODUL-1127 m-form : coquille dans la traduction française des messages

- src/components/form/control-directive.ts
- src/utils/form/abstract-control.ts
Fix max call stack exceeded in the when using control directive
> Fix max call stack exceeded in the when using control directive

- src/utils/http/http-param-serializer.ts
- src/utils/http/http.spec.ts
Add encoding so that ?token=lksjadf==#sjhdfdfas becomes ?token=lksjadf%3D%3D%23sjhdfdfas
The removal of qs.stringify brought up this issue.
https://jira.dti.ulaval.ca/browse/ENA2-7102
> Add encoding to value of query string

- src/utils/form/form-group.ts
Used standard VueJs operators to add and delete an item in an array
> MODUL-1153 - M-Form not reactive when dynamically adding controls to form groups

- src/components/character-count/__snapshots__/character-count.spec.ts.snap
- src/components/character-count/character-count.html
- src/components/menu/menu-item/menu-item.html
- src/components/transitions/accordion-transition/__snapshots__/accordion-transition.stories.ts.snap
- src/components/transitions/accordion-transition/accordion-transition.html
- src/components/transitions/accordion-transition/accordion-transition.stories.ts
- src/components/transitions/accordion-transition/accordion-transition.ts
- src/components/transitions/slide-transition/__snapshots__/slide-transition.stories.ts.snap
- src/components/transitions/slide-transition/slide-transition.html
- src/components/transitions/slide-transition/slide-transition.sandbox.html
- src/components/transitions/slide-transition/slide-transition.scss
- src/components/transitions/slide-transition/slide-transition.stories.ts
- src/components/transitions/slide-transition/slide-transition.ts
- src/components/validation-message/__snapshots__/validation-message.spec.ts.snap
- src/components/validation-message/validation-message.html
* Renommer la prop `transition:boolean` par `disabled:boolean` du composant `m-accordion-transition`
* Lorsque la prop `transition = false` ne pas effectuer le `this.$scrollTo` de la function `transitionEnter()`
https://jira.dti.ulaval.ca/browse/MODUL-1149
Rename the prop `transition: boolean` by `disabled: boolean` for component `m-accordion-transition`
> MODUL-1149: Ameliorer slide transition

- src/components/avatar/avatar.html
- src/components/avatar/avatar.scss
- src/components/avatar/avatar.spec.ts
- src/components/avatar/avatar.stories.ts
- src/components/avatar/avatar.ts
Dans le m-avatar, j'ai ajouté une meilleure gestion du focus. Les boîtes bleus sera visible uniquement lors de la navigation avec TAB. J'en ai profité pour faire une meilleure gestion du mobile (touch). Lorsqu'on clique sur l'avatar pour une première fois, on affiche l'effet de survol et si on reclick dessus, l'action est appelée. 
https://jira.dti.ulaval.ca/browse/MODUL-1152
**BREAKING CHANGE:** In the m-avatar, the parameter in the scoped-slot #content named "hover" is now called "contentVisible".
> MODUL-1152 - Gestion focus avatar

- package.json
Dans le but d'unifier graduellement les composantes-modul vers la nouvelle syntaxe des slots vue 2.6.4+(https://vuejs.org/v2/guide/components-slots.html#Named-Slots)  tel que discuté dans #1097  
Je propose de bumpé la version minimal requise de vue a 2.6.4 + au lieu de 2.5.9 . 
Selon ce que j'ai vu dans ena2 et ael il ne devrait pas y avoir d'impact dans ces projets.
**modul now required vue 2.6.4+** to ensure your project meets the required peer depency run `npm install ` you should not see any peer dependencies warning regardins modul-component
if a warning occur , run this command to update Vue
`npm update vue`
> Updated Vue peer dependency to 2.6.4+

- src/components/dialog/dialog.html
- src/components/dialog/dialog.scss
Le texte de la slot par défaut du dialogue est trop gros. (voir photo du [billet jira](https://jira.dti.ulaval.ca/browse/MODUL-1165))
Sortir la slot par défaut de la **div.m-dialog__mesage**.
https://jira.dti.ulaval.ca/browse/MODUL-1165
> MODUL-1165: Le texte de la slot par défaut du dialogue est trop gros.

- src/components/error-pages/error-access-denied/__snapshots__/error-access-denied.stories.ts.snap
- src/components/error-pages/error-browser-not-supported/__snapshots__/error-browser-not-supported.stories.ts.snap
- src/components/error-pages/error-config-not-supported/__snapshots__/error-config-not-supported.stories.ts.snap
- src/components/error-pages/error-cookies-not-supported/__snapshots__/error-cookies-not-supported.stories.ts.snap
- src/components/error-pages/error-page-not-found/__snapshots__/error-page-not-found.stories.ts.snap
- src/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
- src/components/link/__snapshots__/link.stories.ts.snap
- src/components/link/link.html
- src/components/link/link.scss
- src/components/link/link.stories.ts
- src/components/link/link.ts
- src/components/tooltip/__snapshots__/tooltip.spec.ts.snap
> MODUL-1162 - apply stroke in m-link only with 'svg__chevron'
